var resource_url = 'https://jjinventorysystem.com/devtest/dlm_lmt/';

var aucmapObj = {

    "1":	"CAA Tohoku",
    "2":	"CAA Tokyo",
    "3":	"CAA Chubu",
    "4":	"CAA Gifu",
    "5":	"HAA Kobe",
    "6":	"Kansai Matsubara AA",
    "7":	"JAA",
    "10":	"Honda Hokkaido",
    "11":	"Honda Sendai",
    "12":	"Honda Tokyo",
    "13":	"Honda Nagoya",
    "14":	"Honda Kansai",
    "15":	"Honda Kyushu",
    "16":	"TAA Tohoku",
    "17":	"TAA Yokohama",
    "18":	"TAA Kantou",
    "19":	"TAA Chubu",
    "20":	"TAA Kinki",
    "21":	"TAA Hiroshima",
    "22":	"TAA Kyushu",
    "23":	"TAA Minami Kyushu",
    "25":	"AUCNET",
    "26":	"AUCNET Shared Inventory",
    "28":	"ARAI Sendai",
    "29":	"ARAI Oyama",
    "30":	"ARAI Bayside",
    "31":	"ARAI Oyama VT",
    "33":	"NAA Tokyo",
    "34":	"NAA Tokyo Nyusatsu",
    "35":	"NAA Nagoya",
    "36":	"NAA Nagoya Nyusatsu",
    "37":	"NAA Osaka",
    "38":	"NAA Osaka Nyusatsu",
    "39":	"LAA Kansai",
    "40":	"LAA Shikoku",
    "41":	"KCAA Yamaguchi",
    "42":	"KCAA Fukuoka",
    "43":	"KCAA Minami Kyushu",
    "48":	"JU Hokkaido",
    "51":	"JU Aomori",
    "52":	"JU Akita",
    "53":	"JU Niigata",
    "54":	"JU Fukushima",
    "55":	"JU Miyagi",
    "56":	"JU Yamagata",
    "57":	"JU Ishikawa",
    "58":	"JU Fukui",
    "59":	"JU Ibaraki",
    "60":	"JU Kanagawa",
    "61":	"JU Gunma",
    "62":	"JU Saitama",
    "63":	"JU Shizuoka",
    "64":	"JU Chiba",
    "65":	"JU Tokyo",
    "66":	"JU Tochigi",
    "67":	"JU Toyama",
    "68":	"JU Nagano",
    "70":	"JU Aichi",
    "71":	"JU Mie",
    "73":	"LAA Okayama",
    "74":	"JU Gifu",
    "78":	"JU Nara",
    "79":	"JU Hiroshima",
    "80":	"JU Yamaguchi",
    "81":	"JU Oita",
    "82":	"JU Okinawa",
    "84":	"JU Kumamoto",
    "86":	"JU Fukuoka",
    "87":	"JU Miyazaki",
    "88":	"SAA Hamamatsu",
    "89":	"BAYAUC",
    "90":	"MIRIVE",
    "91":	"HERO",
    "93":	"SAA Sapporo",
    "95":	"ZIP Osaka",
    "111":	"Isuzu Makuhari",
    "113":	"Isuzu Kobe",
    "114":	"KAA Kyoto",
    "117":	"NAA Fukuoka",
    "119":	"Isuzu Kyushu",
    "139":	"ORIX Sendai Nyusatsu",
    "140":	"ORIX Atsugi Nyusatsu",
    "142":	"ORIX Kobe Nyusatsu",
    "143":	"TAA Hokkaido",
    "146":	"NPS Tokyo Nyusatsu",
    "147":	"NPS Osaka Nyusatsu",
    "148":	"ORIX Fukuoka Nyusatsu",
    "163":	"TAA Shikoku",
    "165":	"IAA Osaka",
    "192":	"NPS Sendai Nyusatsu",
    "193":	"NPS Fukuoka Nyusatsu",
    "194":	"LUM Tokyo Nyusatsu",
    "195":	"LUM Kobe Nyusatsu",
    "196":	"LUM Sapporo Nyusatsu",
    "197":	"LUM Nagoya Nyusatsu",
    "198":	"LUM Fukuoka Nyusatsu",
    "205":	"JAA",
    "206":	"JU Yamanashi",
    "208":	"ISUZU Shared Inventory",
    "211":	"NPS Tochigi Nyusatsu",
    "212":	"SAKURA Nyusatsu",
    "214":	"TAA",
    "216":	"NPS Gifu Nyusatsu",
    "217":	"AEP Nyusatsu",
    "219":	"NPS Tomakomai Nyusatsu",
    "221":	"HINO UT&E Hidaka Nyusatsu",
    "222":	"HINO UT&E Kobe Nyusatsu",
    "223":	"HINO UT&E Hansya Nyusatsu",
    "224":	"JCRA Kenki Nyusatsu",
    "225":	"AUC-TRUCK Shared Inventory",
    "226":	"BCN Shared Inventory",
    "227":	"JU Shared Inventory",
    "228":	"IAA Osaka Shared Inventory",
    "231":	"NISSAN Osaka",
    "235":	"YANASE and AUCNET",
    "236":	"Aucnet Hyakuretsu",
    "237":	"zero.carsele Hokkaido Nyusatsu",
    "238":	"zero.carsele Sendai Nyusatsu",
    "239":	"zero.carsele Chiba Nyusatsu",
    "240":	"zero.carsele Shonan Nyusatsu",
    "241":	"zero.carsele Chubu Nyusatsu",
    "242":	"zero.carsele Osaka Nyusatsu",
    "243":	"zero.carsele Hakata Nyusatsu",
    "250":	"IPA Tokyo Nyusatsu",
    "251":	"IPA Kobe Nyusatsu",
    "252":	"IPA Fukuoka Nyusatsu",
    "253":	"ARAI Kenki",
    "958":	"ORIX One Price",
    "991":	"One Price",

    "ãƒ›ãƒ³ãƒ€æ±äº¬": "Honda Tokyo",
    "ãƒ›ãƒ³ãƒ€é–¢è¥¿": "Honda Kansai",
    "ãƒ›ãƒ³ãƒ€åå¤å±‹": "Honda Nagoya",
    "ãƒ›ãƒ³ãƒ€ä¹å·ž": "Honda Kyushu",
    "ãƒ›ãƒ³ãƒ€ä»™å°": "Honda Sendai",
    "ãƒ›ãƒ³ãƒ€åŒ—æµ·é“": "Honda Hokkaido",
    "JUæ±äº¬": "JU Tokyo",




    "CAAå²é˜œ": "CAA Gifu",
    "CAAæ±åŒ—": "CAA Tohoku",
    "TAAè¿‘ç•¿": "TAA Kinki",
    "TAAä¹å·ž": "TAA Kyushu",
    "TAAå—ä¹å·ž": "TAA Minami Kyushu",
    "TAAåºƒå³¶": "TAA Hiroshima",
    "TAAå››å›½": "TAA Shikoku",
    "ï¼«ï¼¡ï¼¡äº¬éƒ½": "KAA Kyoto",
    "ã‚¢ãƒ©ã‚¤ä»™å°": "ARAI Sendai",
    "ã‚¢ãƒ©ã‚¤å»ºæ©Ÿ": "ARAI Kenki",
    "JUåŸ¼çŽ‰": "JU Saitama",
    "JUé™å²¡": "JU Shizuoka",
    "JUé•·é‡Ž": "JU Nagano",
    "JUä¸‰é‡": "JU Mie",
    "JUé’æ£®": "JU Aomori",
    "JUç¦äº•": "JU Fukui",
    "NAAç¦å²¡": "NAA Fukuoka",
    "SAAæœ­å¹Œ": "SAA Sapporo",
    "CAAä¸­éƒ¨": "CAA Chubu",
    "ãƒ™ã‚¤ãƒ»ã‚ªãƒ¼ã‚¯": "BAYAUC",
    "ãƒ™ã‚¤ã‚ªãƒ¼ã‚¯": "BAYAUC",
    "IAAå¤§é˜ª": "IAA Osaka",
    "LAAå››å›½": "LAA Shikoku",
    "ãƒ’ãƒ¼ãƒ­ãƒ¼": "HERO",
    "ãƒŸãƒ©ã‚¤ãƒ–": "MIRIVE",
    "JUèŒ¨åŸŽ": "JU Ibaraki",
    "JUçŸ³å·": "JU Ishikawa",
    "JUç†Šæœ¬": "JU Kumamoto",
    "JUç§‹ç”°": "JU Akita",
    "JUå¤§åˆ†": "JU Oita",
    "TAAé–¢æ±": "TAA Kantou",
    "TAAä¸­éƒ¨": "TAA Chubu",
    "TAAæ±åŒ—": "TAA Tohoku",
    "TAAåŒ—æµ·é“": "TAA Hokkaido",
    "KCAAç¦å²¡": "KCAA Fukuoka",
    "ãƒãƒŠãƒ†ãƒ³å¤§é˜ª": "Hanaten Osaka",
    "ã‚¢ãƒ©ã‚¤å°å±±": "ARAI Oyama",
    "NAAåå¤å±‹": "NAA Nagoya",
    "NAAå¤§é˜ª": "NAA Osaka",
    "NAAã‚ªãƒ¼ã‚µã‚«": "NAA Osaka",
    "JUæ„›çŸ¥": "JU Aichi",
    "JUç¦å³¶": "JU Fukushima",
    "JUç¾¤é¦¬": "JU Gunma",
    "JUå¯Œå±±": "JU Toyama",
    "JUå®®å´Ž": "JU Miyazaki",
    "ZIPå¤§é˜ª": "ZIP Osaka",
    "SAAæµœæ¾": "SAA Hamamatsu",
    "JUç¦å²¡": "JU Fukuoka",
    "JUå®®åŸŽ": "JU Miyagi",
    "JUåƒè‘‰": "JU Chiba",
    "JUæ–°æ½Ÿ": "JU Niigata",
    "JUæ ƒæœ¨": "JU Tochigi",
    "NAAæ±äº¬": "NAA Tokyo",
    "HAAç¥žæˆ¸": "HAA Kobe",
    "JUå²é˜œ": "JU Gifu",
    "JUå¥ˆè‰¯": "JU Nara",
    "JUå±±å½¢": "JU Yamagata",
    "TAAæ¨ªæµœ": "TAA Yokohama",
    "ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆ": "AUCNET",
    "æ—¥ç”£å¤§é˜ª": "NISSAN Osaka",
    "CAAæ±äº¬": "CAA Tokyo",
    "JUå±±å£": "JU Yamaguchi",
    "IPAæ±äº¬å…¥æœ­ä¼š": "IPA Tokyo Nyusatsu",
    "ã‚ªãƒªãƒƒã‚¯ã‚¹ç¥žæˆ¸å…¥æœ­ä¼š": "ORIX Kobe Nyusatsu",
    "ã‚ªãƒªãƒƒã‚¯ã‚¹ç¦å²¡å…¥æœ­ä¼š": "ORIX Fukuoka Nyusatsu",
    "ã‚ªãƒªãƒƒã‚¯ã‚¹ä»™å°å…¥æœ­ä¼š": "ORIX Sendai Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«æ±äº¬å…¥æœ­ä¼š": "NPS Tokyo Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«å¤§é˜ªå…¥æœ­ä¼š": "NPS Osaka Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«ä»™å°å…¥æœ­ä¼š": "NPS Sendai Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«ç¦å²¡å…¥æœ­ä¼š": "NPS Fukuoka Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«æ ƒæœ¨å…¥æœ­ä¼š": "NPS Tochigi Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«å²é˜œå…¥æœ­ä¼š": "NPS Gifu Nyusatsu",
    "æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«è‹«å°ç‰§å…¥æœ­ä¼š": "NPS Tomakomai Nyusatsu",
    "LUMåå¤å±‹å…¥æœ­ä¼š": "LUM Nagoya Nyusatsu",
    "LUMç¦å²¡å…¥æœ­ä¼š": "LUM Fukuoka Nyusatsu",
    "AEPå…¥æœ­": "AEP Nyusatsu",
    "SAKURAå…¥æœ­": "SAKURA Nyusatsu",
    "KCAAå—ä¹å·ž": "KCAA Minami Kyushu",
    "KAAäº¬éƒ½åºœ": "KAA Kyoto",
    "ã„ã™ã‚žå¹•å¼µ": "Isuzu Makuhari",
    "IPAç¦å²¡å…¥æœ­ä¼š": "IPA Fukuoka Nyusatsu",
    "JAA": "JAA",
    "ã‚ªãƒªãƒƒã‚¯ã‚¹åŽšæœ¨å…¥æœ­ä¼š": "ORIX Atsugi Nyusatsu",
    "LUMæ±äº¬å…¥æœ­ä¼š": "LUM Tokyo Nyusatsu",
    "ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆç™¾çƒˆå•†è«‡": "Aucnet Hyakuretsu",
    "LAAé–¢è¥¿": "LAA Kansai",
    "JUåºƒå³¶": "JU Hiroshima",
    "JUç¥žå¥ˆå·": "JU Kanagawa",
    "ã„ã™ã‚žä¹å·ž": "Isuzu Kyushu",
    "IPAç¥žæˆ¸å…¥æœ­ä¼š": "IPA Kobe Nyusatsu",
    "LUMåŒ—æµ·é“å…¥æœ­ä¼š": "LUM Sapporo Nyusatsu",
    "LUMç¥žæˆ¸å…¥æœ­ä¼š": "LUM Kobe Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬æ¹˜å—å…¥æœ­ä¼š": "zero.carsele Shonan Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬ä¸­éƒ¨å…¥æœ­ä¼š": "zero.carsele Chubu Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬å¤§é˜ªå…¥æœ­ä¼š": "zero.carsele Osaka Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬æ¹˜å—å…¥æœ­ä¼š": "zero.carsele Shonan Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬ä¸­éƒ¨å…¥æœ­ä¼š": "zero.carsele Chubu Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬å¤§é˜ªå…¥æœ­ä¼š": "zero.carsele Osaka Nyusatsu",
    "JUæ²–ç¸„": "JU Okinawa",
    "JUåŒ—æµ·é“": "JU Hokkaido",
    "æ—¥é‡ŽUT&Eæ—¥é«˜å…¥æœ­ä¼š": "HINO UT&E Hidaka Nyusatsu",
    "æ—¥é‡ŽUT&Eç¥žæˆ¸å…¥æœ­ä¼š": "HINO UT&E Kobe Nyusatsu",
    "æ—¥é‡ŽUT&Eè²©ç¤¾å…¥æœ­ä¼š": "HINO UT&E Hansya Nyusatsu",
    "ã‚¢ãƒ©ã‚¤ãƒ™ã‚¤ã‚µã‚¤ãƒ‰": "ARAI Bayside",
    "LAAå²¡å±±": "LAA Okayama",
    "KCAAå±±å£": "KCAA Yamaguchi",
    "ã„ã™ã‚žç¥žæˆ¸": "Isuzu Kobe",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åŒ—æµ·é“å…¥æœ­ä¼š": "zero.carsele Hokkaido Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬ä»™å°å…¥æœ­ä¼š": "zero.carsele Sendai Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åƒè‘‰å…¥æœ­ä¼š": "zero.carsele Chiba Nyusatsu",
    "ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åšå¤šå…¥æœ­ä¼š": "zero.carsele Hakata Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬åŒ—æµ·é“å…¥æœ­ä¼š": "zero.carsele Hokkaido Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬ä»™å°å…¥æœ­ä¼š": "zero.carsele Sendai Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬åƒè‘‰å…¥æœ­ä¼š": "zero.carsele Chiba Nyusatsu",
    "ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬åšå¤šå…¥æœ­ä¼š": "zero.carsele Hakata Nyusatsu",
    "JCRAå»ºæ©Ÿå…¥æœ­ä¼š": "JCRA Kenki Nyusatsu",
    "JUå±±æ¢¨": "JU Yamanashi",
    "ã‚¢ãƒ©ã‚¤å°å±±VT": "ARAI Oyama VT",
    "ãƒ¤ãƒŠã‚»andã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆ": "YANASE and AUCNET",
    "NAAæ±äº¬å…¥æœ­ä¼š": "NAA Tokyo Nyusatsu",
    "NAAåå¤å±‹å…¥æœ­ä¼š": "NAA Nagoya Nyusatsu",
    "NAAå¤§é˜ªå…¥æœ­ä¼š": "NAA Osaka Nyusatsu",
    "ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆå…±æœ‰åœ¨åº«": "AUCNET Shared Inventory",
    "ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆãƒˆãƒ©ãƒƒã‚¯å…±æœ‰åœ¨åº«": "AUC-TRUCK Shared Inventory",
    "JAA HAAå…±æœ‰åœ¨åº«": "JAA   HAA Shared Inventory",
    "ã„ã™ã‚žå…±æœ‰åœ¨åº«": "ISUZU Shared Inventory",
    "TAA CAAå…±æœ‰åœ¨åº«": "TAA   CAA Shared Inventory",
    "BCNå…±æœ‰åœ¨åº«": "BCN Shared Inventory",
    "JUå…±æœ‰åœ¨åº«": "JU Shared Inventory",
    "IAAå¤§é˜ªå…±æœ‰åœ¨åº«": "IAA Osaka Shared Inventory",
    "é–¢è¥¿æ¾åŽŸAA":"Kansai Matsubara AA"
};

var aucmap_je = [
    ["ãƒ›ãƒ³ãƒ€æ±äº¬", "Honda Tokyo"],
    ["ãƒ›ãƒ³ãƒ€é–¢è¥¿", "Honda Kansai"],
    ["ãƒ›ãƒ³ãƒ€åå¤å±‹", "Honda Nagoya"],
    ["ãƒ›ãƒ³ãƒ€ä¹å·ž", "Honda Kyushu"],
    ["ãƒ›ãƒ³ãƒ€ä»™å°", "Honda Sendai"],
    ["ãƒ›ãƒ³ãƒ€åŒ—æµ·é“", "Honda Hokkaido"],
    ["ï¼ªï¼µæ±äº¬", "JU Tokyo"],
    ["ï¼£ï¼¡ï¼¡å²é˜œ", "CAA Gifu"],
    ["ï¼£ï¼¡ï¼¡æ±åŒ—", "CAA Tohoku"],
    ["ï¼´ï¼¡ï¼¡è¿‘ç•¿", "TAA Kinki"],
    ["ï¼´ï¼¡ï¼¡ä¹å·ž", "TAA Kyushu"],
    ["ï¼´ï¼¡ï¼¡å—ä¹å·ž", "TAA Minami Kyushu"],
    ["ï¼´ï¼¡ï¼¡åºƒå³¶", "TAA Hiroshima"],
    ["ï¼´ï¼¡ï¼¡å››å›½", "TAA Shikoku"],
    ["ã‚¢ãƒ©ã‚¤ä»™å°", "ARAI Sendai"],
    ["ã‚¢ãƒ©ã‚¤å»ºæ©Ÿ", "ARAI Kenki"],
    ["ï¼ªï¼µåŸ¼çŽ‰", "JU Saitama"],
    ["ï¼ªï¼µé™å²¡", "JU Shizuoka"],
    ["ï¼ªï¼µé•·é‡Ž", "JU Nagano"],
    ["ï¼ªï¼µä¸‰é‡", "JU Mie"],
    ["ï¼ªï¼µé’æ£®", "JU Aomori"],
    ["ï¼ªï¼µç¦äº•", "JU Fukui"],
    ["ï¼®ï¼¡ï¼¡ç¦å²¡", "NAA Fukuoka"],
    ["ï¼³ï¼¡ï¼¡æœ­å¹Œ", "SAA Sapporo"],
    ["ï¼£ï¼¡ï¼¡ä¸­éƒ¨", "CAA Chubu"],
    ["ãƒ™ã‚¤ãƒ»ã‚ªãƒ¼ã‚¯", "BAYAUC"],
    ["ãƒ™ã‚¤ã‚ªãƒ¼ã‚¯", "BAYAUC"],
    ["ï¼©ï¼¡ï¼¡å¤§é˜ª", "IAA Osaka"],
    ["ï¼¬ï¼¡ï¼¡å››å›½", "LAA Shikoku"],
    ["ãƒ’ãƒ¼ãƒ­ãƒ¼", "HERO"],
    ["ãƒŸãƒ©ã‚¤ãƒ–", "MIRIVE"],
    ["ï¼ªï¼µèŒ¨åŸŽ", "JU Ibaraki"],
    ["ï¼ªï¼µçŸ³å·", "JU Ishikawa"],
    ["ï¼ªï¼µç†Šæœ¬", "JU Kumamoto"],
    ["ï¼ªï¼µç§‹ç”°", "JU Akita"],
    ["ï¼ªï¼µå¤§åˆ†", "JU Oita"],
    ["ï¼´ï¼¡ï¼¡é–¢æ±", "TAA Kantou"],
    ["ï¼´ï¼¡ï¼¡ä¸­éƒ¨", "TAA Chubu"],
    ["ï¼´ï¼¡ï¼¡æ±åŒ—", "TAA Tohoku"],
    ["ï¼´ï¼¡ï¼¡åŒ—æµ·é“", "TAA Hokkaido"],
    ["ï¼«ï¼£ï¼¡ï¼¡ç¦å²¡", "KCAA Fukuoka"],
    ["ãƒãƒŠãƒ†ãƒ³å¤§é˜ª", "Hanaten Osaka"],
    ["ã‚¢ãƒ©ã‚¤å°å±±", "ARAI Oyama"],
    ["ï¼®ï¼¡ï¼¡åå¤å±‹", "NAA Nagoya"],
    ["ï¼®ï¼¡ï¼¡å¤§é˜ª", "NAA Osaka"],
    ["ï¼ªï¼µæ„›çŸ¥", "JU Aichi"],
    ["ï¼ªï¼µç¦å³¶", "JU Fukushima"],
    ["ï¼ªï¼µç¾¤é¦¬", "JU Gunma"],
    ["ï¼ªï¼µå¯Œå±±", "JU Toyama"],
    ["ï¼ªï¼µå®®å´Ž", "JU Miyazaki"],
    ["ï¼ºï¼©ï¼°å¤§é˜ª", "ZIP Osaka"],
    ["ï¼³ï¼¡ï¼¡æµœæ¾", "SAA Hamamatsu"],
    ["ï¼ªï¼µç¦å²¡", "JU Fukuoka"],
    ["ï¼ªï¼µå®®åŸŽ", "JU Miyagi"],
    ["ï¼ªï¼µåƒè‘‰", "JU Chiba"],
    ["ï¼ªï¼µæ–°æ½Ÿ", "JU Niigata"],
    ["ï¼ªï¼µæ ƒæœ¨", "JU Tochigi"],
    ["ï¼®ï¼¡ï¼¡æ±äº¬", "NAA Tokyo"],
    ["ï¼¨ï¼¡ï¼¡ç¥žæˆ¸", "HAA Kobe"],
    ["ï¼ªï¼µå²é˜œ", "JU Gifu"],
    ["ï¼ªï¼µå¥ˆè‰¯", "JU Nara"],
    ["ï¼ªï¼µå±±å½¢", "JU Yamagata"],
    ["ï¼´ï¼¡ï¼¡æ¨ªæµœ", "TAA Yokohama"],
    ["ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆ", "AUCNET"],
    ["æ—¥ç”£å¤§é˜ª", "NISSAN Osaka"],
    ["ï¼£ï¼¡ï¼¡æ±äº¬", "CAA Tokyo"],
    ["ï¼ªï¼µå±±å£", "JU Yamaguchi"],
    ["IPAæ±äº¬å…¥æœ­ä¼š", "IPA Tokyo Nyusatsu"],
    ["ã‚ªãƒªãƒƒã‚¯ã‚¹ç¥žæˆ¸å…¥æœ­ä¼š", "ORIX Kobe Nyusatsu"],
    ["ã‚ªãƒªãƒƒã‚¯ã‚¹ç¦å²¡å…¥æœ­ä¼š", "ORIX Fukuoka Nyusatsu"],
    ["ã‚ªãƒªãƒƒã‚¯ã‚¹ä»™å°å…¥æœ­ä¼š", "ORIX Sendai Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«æ±äº¬å…¥æœ­ä¼š", "NPS Tokyo Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«å¤§é˜ªå…¥æœ­ä¼š", "NPS Osaka Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«ä»™å°å…¥æœ­ä¼š", "NPS Sendai Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«ç¦å²¡å…¥æœ­ä¼š", "NPS Fukuoka Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«æ ƒæœ¨å…¥æœ­ä¼š", "NPS Tochigi Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«å²é˜œå…¥æœ­ä¼š", "NPS Gifu Nyusatsu"],
    ["æ—¥ç”£ãƒ—ãƒ©ã‚¶ã‚½ãƒ«è‹«å°ç‰§å…¥æœ­ä¼š", "NPS Tomakomai Nyusatsu"],
    ["LUMåå¤å±‹å…¥æœ­ä¼š", "LUM Nagoya Nyusatsu"],
    ["LUMç¦å²¡å…¥æœ­ä¼š", "LUM Fukuoka Nyusatsu"],
    ["AEPå…¥æœ­", "AEP Nyusatsu"],
    ["SAKURAå…¥æœ­", "SAKURA Nyusatsu"],
    ["ï¼«ï¼£ï¼¡ï¼¡å—ä¹å·ž", "KCAA Minami Kyushu"],
    ["ï¼«ï¼¡ï¼¡äº¬éƒ½åºœ", "KAA Kyoto"],
    ["ï¼«ï¼¡ï¼¡äº¬éƒ½", "KAA Kyoto"],
    ["ã„ã™ã‚žå¹•å¼µ", "Isuzu Makuhari"],
    ["IPAç¦å²¡å…¥æœ­ä¼š", "IPA Fukuoka Nyusatsu"],
    ["ï¼ªï¼¡ï¼¡", "JAA"],
    ["ã‚ªãƒªãƒƒã‚¯ã‚¹åŽšæœ¨å…¥æœ­ä¼š", "ORIX Atsugi Nyusatsu"],
    ["LUMæ±äº¬å…¥æœ­ä¼š", "LUM Tokyo Nyusatsu"],
    ["ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆç™¾çƒˆå•†è«‡", "Aucnet Hyakuretsu"],
    ["ï¼¬ï¼¡ï¼¡é–¢è¥¿", "LAA Kansai"],
    ["ï¼ªï¼µåºƒå³¶", "JU Hiroshima"],
    ["ï¼ªï¼µç¥žå¥ˆå·", "JU Kanagawa"],
    ["ã„ã™ã‚žä¹å·ž", "Isuzu Kyushu"],
    ["IPAç¥žæˆ¸å…¥æœ­ä¼š", "IPA Kobe Nyusatsu"],
    ["LUMåŒ—æµ·é“å…¥æœ­ä¼š", "LUM Sapporo Nyusatsu"],
    ["LUMç¥žæˆ¸å…¥æœ­ä¼š", "LUM Kobe Nyusatsu"],
    ["ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬æ¹˜å—å…¥æœ­ä¼š", "zero.carsele Shonan Nyusatsu"],
    ["ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬ä¸­éƒ¨å…¥æœ­ä¼š", "zero.carsele Chubu Nyusatsu"],
    ["ã‚¼ãƒ­ãƒ»ã‚«ãƒ¼ã‚»ãƒ¬å¤§é˜ªå…¥æœ­ä¼š", "zero.carsele Osaka Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬æ¹˜å—å…¥æœ­ä¼š", "zero.carsele Shonan Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬ä¸­éƒ¨å…¥æœ­ä¼š", "zero.carsele Chubu Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬å¤§é˜ªå…¥æœ­ä¼š", "zero.carsele Osaka Nyusatsu"],
    ["ï¼ªï¼µæ²–ç¸„", "JU Okinawa"],
    ["ï¼ªï¼µåŒ—æµ·é“", "JU Hokkaido"],
    ["æ—¥é‡ŽUT&Eæ—¥é«˜å…¥æœ­ä¼š", "HINO UT&E Hidaka Nyusatsu"],
    ["æ—¥é‡ŽUT&Eç¥žæˆ¸å…¥æœ­ä¼š", "HINO UT&E Kobe Nyusatsu"],
    ["æ—¥é‡ŽUT&Eè²©ç¤¾å…¥æœ­ä¼š", "HINO UT&E Hansya Nyusatsu"],
    ["ã‚¢ãƒ©ã‚¤ãƒ™ã‚¤ã‚µã‚¤ãƒ‰", "ARAI Bayside"],
    ["ï¼¬ï¼¡ï¼¡å²¡å±±", "LAA Okayama"],
    ["ï¼«ï¼£ï¼¡ï¼¡å±±å£", "KCAA Yamaguchi"],
    ["ã„ã™ã‚žç¥žæˆ¸", "Isuzu Kobe"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åŒ—æµ·é“å…¥æœ­ä¼š", "zero.carsele Hokkaido Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬ä»™å°å…¥æœ­ä¼š", "zero.carsele Sendai Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åƒè‘‰å…¥æœ­ä¼š", "zero.carsele Chiba Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åšå¤šå…¥æœ­ä¼š", "zero.carsele Hakata Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åŒ—æµ·é“å…¥æœ­ä¼š", "zero.carsele Hokkaido Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬ä»™å°å…¥æœ­ä¼š", "zero.carsele Sendai Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åƒè‘‰å…¥æœ­ä¼š", "zero.carsele Chiba Nyusatsu"],
    ["ã‚¼ãƒ­ã‚«ãƒ¼ã‚»ãƒ¬åšå¤šå…¥æœ­ä¼š", "zero.carsele Hakata Nyusatsu"],
    ["JCRAå»ºæ©Ÿå…¥æœ­ä¼š", "JCRA Kenki Nyusatsu"],
    ["ï¼ªï¼µå±±æ¢¨", "JU Yamanashi"],
    ["ã‚¢ãƒ©ã‚¤å°å±±ï¼¶ï¼´", "ARAI Oyama VT"],
    ["ãƒ¤ãƒŠã‚»andã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆ", "YANASE and AUCNET"],
    ["ï¼®ï¼¡ï¼¡æ±äº¬å…¥æœ­ä¼š", "NAA Tokyo Nyusatsu"],
    ["ï¼®ï¼¡ï¼¡åå¤å±‹å…¥æœ­ä¼š", "NAA Nagoya Nyusatsu"],
    ["ï¼®ï¼¡ï¼¡å¤§é˜ªå…¥æœ­ä¼š", "NAA Osaka Nyusatsu"],
    ["ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆå…±æœ‰åœ¨åº«", "AUCNET Shared Inventory"],
    ["ã‚ªãƒ¼ã‚¯ãƒãƒƒãƒˆãƒˆãƒ©ãƒƒã‚¯å…±æœ‰åœ¨åº«", "AUC-TRUCK Shared Inventory"],
    ["JAA HAAå…±æœ‰åœ¨åº«", "JAA   HAA Shared Inventory"],
    ["ã„ã™ã‚žå…±æœ‰åœ¨åº«", "ISUZU Shared Inventory"],
    ["TAA CAAå…±æœ‰åœ¨åº«", "TAA   CAA Shared Inventory"],
    ["BCNå…±æœ‰åœ¨åº«", "BCN Shared Inventory"],
    ["JUå…±æœ‰åœ¨åº«", "JU Shared Inventory"],
    ["IAAå¤§é˜ªå…±æœ‰åœ¨åº«", "IAA Osaka Shared Inventory"]
];

var colormap = {

};

var carnames = [
    ["FJï½¸ï¾™ï½°ï½»ï¾žï½°", "FJ Cruiser"],
    ["WILLï½»ï½²ï¾Œï½§", "WILL cipher"],
    ["ï½±ï½²ï½¼ï½½", "Isis"],
    ["ï½±ï½¸ï½±", "Aqua"],
    ["ï½±ï¾Šï¾žï¾›ï¾", "Avalon"],
    ["ï½±ï¾ï¾žï¾ï½¼ï½½ï½¾ï¾€ï¾žï¾", "Avensis Sedan"],
    ["ï½±ï¾ï¾žï¾ï½¼ï½½ï¾œï½ºï¾žï¾", "Avensis Wagon"],
    ["ï½±ï¾˜ï½µï¾", "Arion"],
    ["ï½±ï¾˜ï½½ï¾„", "Aristo"],
    ["ï½±ï¾™ï¾ƒï½¯ï¾‚ï½§", "Altezza"],
    ["ï½±ï¾™ï¾ƒï½¯ï¾‚ï½§ï½¼ï¾žï½°ï¾€", "Altezza Zita"],
    ["ï½±ï¾™ï¾Œï½§ï½°ï¾„ï¾ž", "Alphard"],
    ["ï½±ï¾šï½¯ï½¸ï½½", "Alex"],
    ["ï½²ï½½ï¾„", "Ist"],
    ["ï½²ï¾Œï¾Ÿï½»ï¾‘", "Ipsum"],
    ["ï½³ï½¨ï½¯ï½¼ï½­", "Wish"],
    ["ï½³ï½¨ï¾ï¾€ï¾žï¾‘", "Wyndham"],
    ["ï½³ï¾žï½§ï¾ï½¶ï¾žï½°ï¾„ï¾ž", "Vanguard"],
    ["ï½³ï¾žï½¨ï½¯ï¾‚", "Vitz"],
    ["ï½³ï¾žï½ªï¾™ï¾Œï½§ï½²ï½±", "Velfire"],
    ["ï½³ï¾žï½ªï¾›ï½¯ï½»", "Velosa"],
    ["ï½³ï¾žï½«ï½¸ï½¼ï½°", "Voxy"],
    ["ï½³ï¾žï½«ï¾™ï¾‚", "Volz"],
    ["ï½´ï½½ï½¸ï½§ï½²ï½±", "Esquire"],
    ["ï½´ï½½ï¾ƒï½¨ï¾", "Estima"],
    ["ï½´ï½½ï¾ƒï½¨ï¾T L", "Estima T   L"],
    ["ï½´ï½½ï¾ƒï½¨ï¾ï½´ï¾ï½°ï¾…", "Estima Emina"],
    ["ï½´ï½½ï¾ƒï½¨ï¾ï¾Šï½²ï¾Œï¾žï¾˜", "Estima Hybrid"],
    ["ï½´ï½½ï¾ƒï½¨ï¾ï¾™ï½¼ï½°ï¾€ï¾ž", "Estima Lucida"],
    ["ï½µï½°ï¾Šï¾Ÿ", "Opa"],
    ["ï½µï½°ï¾˜ï½½", "Auris"],
    ["ï½µï¾˜ï½¼ï¾žï¾", "Origin"],
    ["ï½¶ï¾‘ï¾˜", "Camry"],
    ["ï½¶ï¾‘ï¾˜ï½¸ï¾žï¾—ï½¼ï½±", "Camry gracia"],
    ["ï½¶ï¾‘ï¾˜ï½¸ï¾žï¾—ï½¼ï½±ï¾œï½ºï¾žï¾", "Camry Gracia Wagon"],
    ["ï½¶ï¾‘ï¾›ï½°ï¾„ï¾ž", "Cam log"],
    ["ï½¶ï¾˜ï½°ï¾…", "Carina"],
    ["ï½¶ï¾˜ï½°ï¾…ED", "Carina ED"],
    ["ï½¶ï¾˜ï½°ï¾…ï½»ï½°ï¾Œ", "Karina Surf"],
    ["ï½¶ï¾˜ï½°ï¾…ï¾Šï¾žï¾", "Carina van"],
    ["ï½¶ï¾™ï¾ƒï¾žï½¨ï¾…", "Cardinal"],
    ["ï½¶ï¾™ï¾ƒï¾žï½¨ï¾…ï¾Šï¾žï¾", "Cardinal van"],
    ["ï½¶ï¾šï¾", "Karen"],
    ["ï½¶ï¾›ï½°ï¾—", "Corolla"],
    ["ï½¶ï¾›ï½°ï¾—FX", "Corolla FX"],
    ["ï½¶ï¾›ï½°ï¾—â…¡", "Corolla II"],
    ["ï½¶ï¾›ï½°ï¾—ï½±ï½¸ï½¼ï½µ", "Corolla Axio"],
    ["ï½¶ï¾›ï½°ï¾—ï½½ï¾Šï¾Ÿï½¼ï½µ", "Corolla Spacio"],
    ["ï½¶ï¾›ï½°ï¾—ï½¾ï¾šï½½", "Corolla Ceres"],
    ["ï½¶ï¾›ï½°ï¾—ï¾Šï¾žï¾", "Corolla Van"],
    ["ï½¶ï¾›ï½°ï¾—ï¾Œï½¨ï¾™ï¾€ï¾žï½°", "Corolla filler"],
    ["ï½¶ï¾›ï½°ï¾—ï¾—ï¾ï½¸ï½½", "Corolla Runs"],
    ["ï½¶ï¾›ï½°ï¾—ï¾™ï¾ï½µï¾", "Corolla Lumion"],
    ["ï½¶ï¾›ï½°ï¾—ï¾šï¾‹ï¾žï¾", "Corolla Levin"],
    ["ï½¶ï¾›ï½°ï¾—ï¾œï½ºï¾žï¾", "Corolla Wagon"],
    ["ï½¶ï¾žï½²ï½±", "Gaia"],
    ["ï½·ï½¬ï¾Šï¾žï¾˜ï½´", "Cavalier"],
    ["ï½·ï½¬ï¾", "Cami"],
    ["ï½¸ï½²ï½¯ï½¸ï¾ƒï¾žï¾˜ï¾Šï¾žï¾˜ï½°ï¾Šï¾žï¾", "Quick Delivery Van"],
    ["ï½¸ï¾—ï½³ï¾", "Crown"],
    ["ï½¸ï¾—ï½³ï¾ï½´ï½½ï¾ƒï½°ï¾„", "Crown Estate"],
    ["ï½¸ï¾—ï½³ï¾ï½ºï¾ï¾Œï½«ï½°ï¾„", "Crown Comfort"],
    ["ï½¸ï¾—ï½³ï¾ï¾Šï¾žï¾", "Crown van"],
    ["ï½¸ï¾—ï½³ï¾ï¾ï½¼ï¾žï½ªï½½ï¾€", "Crown Majesta"],
    ["ï½¸ï¾—ï½³ï¾ï¾œï½ºï¾žï¾", "Crown Wagon"],
    ["ï½¸ï¾™ï½°ï½¶ï¾žï½°", "Kruger"],
    ["ï½¸ï¾šï½½ï¾€", "Cresta"],
    ["ï½¸ï¾žï¾—ï¾ï¾„ï¾žï¾Šï½²ï½´ï½°ï½½", "Grand Hiace"],
    ["ï½¸ï¾žï¾—ï¾ï¾‹ï¾žï½±", "Gran Via"],
    ["ï½ºï½°ï½½ï¾€ï½°", "Coaster"],
    ["ï½ºï¾™ï½»", "Corsa"],
    ["ï½ºï¾›ï¾…", "Corona"],
    ["ï½ºï¾›ï¾… ï¾ï½°ï½¸â…¡", "Corona Mark II"],
    ["ï½ºï¾›ï¾…ï½´ï½¸ï½¼ï¾Œï¾ž", "Corona XIV"],
    ["ï½ºï¾›ï¾…ï¾Šï¾žï¾", "Corona Bang"],
    ["ï½ºï¾›ï¾…ï¾Œï¾Ÿï¾šï¾ï½µ", "Corona Premio"],
    ["ï½ºï¾ï¾Œï½«ï½°ï¾„", "Comfort"],
    ["ï½»ï½²ï¾‰ï½½", "Sinos"],
    ["ï½»ï½¸ï½¼ï½°ï¾„ï¾ž", "Succeed"],
    ["ï½»ï½¸ï½¼ï½°ï¾„ï¾žï¾Šï¾žï¾", "Succeeded van"],
    ["ï½¼ï½´ï¾ï¾€", "Cienta"],
    ["ï½¼ï¾žï½®ï¾Œï¾žï½»ï¾", "Job san"],
    ["ï½½ï½°ï¾Œï¾Ÿï¾—", "Supra"],
    ["ï½½ï¾€ï½°ï¾šï½¯ï¾„", "Starlet"],
    ["ï½½ï¾Šï¾Ÿï½°ï½·ï½°", "Sparky"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°", "Sprinter"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°ï½¶ï¾˜ï¾Œï¾ž", "Sprinter Caribbean"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°ï¾„ï¾šï¾‰", "Sprinter Trueno"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°ï¾Šï¾žï¾", "Sprinter van"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°ï¾ï¾˜ï¾‰", "Sprinter Marino"],
    ["ï½½ï¾Œï¾Ÿï¾˜ï¾ï¾€ï½°ï¾œï½ºï¾žï¾", "Sprinter Wagon"],
    ["ï½½ï¾ï¾Ÿï½²ï¾„ï¾ž", "Spade"],
    ["ï½¾ï¾Œï¾Ÿï¾€ï½°", "Scepter"],
    ["ï½¾ï¾Œï¾Ÿï¾€ï½°ï¾œï½ºï¾žï¾", "Septa wagon"],
    ["ï½¾ï¾—", "Serra"],
    ["ï½¾ï¾˜ï½¶", "Celica"],
    ["ï½¾ï¾™ï½¼ï½µ", "Celsior"],
    ["ï½¾ï¾ï¾ï½­ï¾˜ï½°", "Century"],
    ["ï½¿ï½±ï¾—", "Soarer"],
    ["ï¾€ï½°ï½¾ï¾™", "Tarcel"],
    ["ï¾€ï½³ï¾ï½´ï½°ï½½ï¾„ï¾—ï½¯ï½¸", "Townace truck"],
    ["ï¾€ï½³ï¾ï½´ï½°ï½½ï¾‰ï½±", "Townace Noah"],
    ["ï¾€ï½³ï¾ï½´ï½°ï½½ï¾Šï¾žï¾", "Townace Van"],
    ["ï¾€ï½³ï¾ï½´ï½°ï½½ï¾œï½ºï¾žï¾", "Town Ace Wagon"],
    ["ï¾€ï¾ï½¸", "Tank"],
    ["ï¾€ï¾žï½²ï¾…", "Dyna"],
    ["ï¾ï½ªï½²ï½»ï½°", "Chaser"],
    ["ï¾‚ï½°ï¾˜ï¾ï½¸ï¾žï¾Šï½²ï½´ï½°ï½½", "Touring Hiace"],
    ["ï¾ƒï¾žï½­ï½´ï½¯ï¾„", "Duet"],
    ["ï¾ƒï¾žï¾˜ï¾Žï¾žï½°ï½²", "Deliboi"],
    ["ï¾„ï¾–ï½´ï½°ï½½", "Toyoace"],
    ["ï¾„ï¾–ï¾€", "Toyota"],
    ["ï¾„ï¾–ï¾€ï½¸ï¾—ï½¼ï½¯ï½¸", "Toyota Classic"],
    ["ï¾„ï¾–ï¾€ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Toyota forklift"],
    ["ï¾„ï¾–ï¾€ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Toyota wheel loader"],
    ["ï¾…ï¾ƒï¾žï½¨ï½±", "Nadia"],
    ["ï¾‰ï½±", "Noah"],
    ["ï¾Šï½²ï½´ï½°ï½½ï½ºï¾ï½­ï½°ï¾€ï½°", "Hiace commuter"],
    ["ï¾Šï½²ï½´ï½°ï½½ï¾„ï¾—ï½¯ï½¸", "Hiace truck"],
    ["ï¾Šï½²ï½´ï½°ï½½ï¾Šï¾žï¾", "Hiace Van"],
    ["ï¾Šï½²ï½´ï½°ï½½ï¾šï½¼ï¾žï½±ï½½", "Hiace Regius"],
    ["ï¾Šï½²ï½´ï½°ï½½ï¾œï½ºï¾žï¾", "Hiace wagon"],
    ["ï¾Šï½²ï¾’ï¾ƒï¾žï½¨ï½¯ï½¸", "Himedic"],
    ["ï¾Šï½²ï¾—ï½¯ï½¸ï½½", "Hilux"],
    ["ï¾Šï½²ï¾—ï½¯ï½¸ï½½ï½»ï½°ï¾Œ", "Hilux Surf"],
    ["ï¾Šï½²ï¾—ï½¯ï½¸ï½½ï¾Šï¾žï¾", "Hilux Van"],
    ["ï¾Šï¾˜ï½±ï½°", "Harrier"],
    ["ï¾Šï¾Ÿï½¯ï½¿", "Passo"],
    ["ï¾Šï¾Ÿï½¯ï½¿ï½¾ï½¯ï¾ƒ", "Passocete"],
    ["ï¾‹ï¾žï½½ï¾€", "Vista"],
    ["ï¾‹ï¾žï½½ï¾€ï½±ï¾™ï¾ƒï¾žï½µ", "Vista Aldeo"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ ï¾’ï½¶ï¾ž", "Pixis mega"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ï½´ï¾Žï¾Ÿï½¯ï½¸", "Pixis Epoch"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ï½¼ï¾žï½®ï½²", "Pixis Joy"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ï½½ï¾ï¾Ÿï½°ï½½", "Pixis space"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ï¾„ï¾—ï½¯ï½¸", "Pixis truck"],
    ["ï¾‹ï¾Ÿï½¸ï½¼ï½½ï¾Šï¾žï¾", "Pixis van"],
    ["ï¾Œï½§ï¾ï½¶ï½°ï½ºï¾ž", "Fan Cargo"],
    ["ï¾Œï¾žï¾˜ï½»ï¾žï½°ï¾„ï¾ž", "Blizzard"],
    ["ï¾Œï¾žï¾šï½²ï¾„ï¾ž", "Blade"],
    ["ï¾Œï¾žï¾šï¾‹ï¾žï½½", "Brevis"],
    ["ï¾Œï¾Ÿï¾—ï½¯ï¾‚", "Platts"],
    ["ï¾Œï¾Ÿï¾˜ï½³ï½½", "Prius"],
    ["ï¾Œï¾Ÿï¾˜ï½³ï½½ ï½±ï¾™ï¾Œï½§", "Prius alpha"],
    ["ï¾Œï¾Ÿï¾˜ï½³ï½½PHV", "Prius PHV"],
    ["ï¾Œï¾Ÿï¾šï¾ï½µ", "Premio"],
    ["ï¾Œï¾Ÿï¾›ï½¸ï¾žï¾š", "Progress"],
    ["ï¾Œï¾Ÿï¾›ï¾…ï½°ï¾„ï¾ž", "Pronado"],
    ["ï¾Œï¾Ÿï¾›ï¾Žï¾žï½¯ï½¸ï½½", "Pro box"],
    ["ï¾Œï¾Ÿï¾›ï¾Žï¾žï½¯ï½¸ï½½ï¾Šï¾žï¾", "Pro box van"],
    ["ï¾ï¾žï¾™ï¾€", "Bertha"],
    ["ï¾Žï¾Ÿï¾™ï¾ƒ", "Porte"],
    ["ï¾ï½°ï½¸X", "Mark X"],
    ["ï¾ï½°ï½¸Xï½¼ï¾žï½µ", "Mark X Geo"],
    ["ï¾ï½°ï½¸â…¡", "Mark â…¡"],
    ["ï¾ï½°ï½¸â…¡ï½¸ï½µï¾˜ï½½", "Mark â…¡ Quoris"],
    ["ï¾ï½°ï½¸â…¡ï¾Šï¾žï¾", "Mark â…¡ Van"],
    ["ï¾ï½°ï½¸â…¡ï¾Œï¾žï¾˜ï½¯ï¾„", "Mark â…¡ Brit"],
    ["ï¾ï½°ï½¸â…¡ï¾œï½ºï¾žï¾", "Mark II Wagon"],
    ["ï¾ï½½ï¾€ï½°ï½´ï½°ï½½ï½»ï½°ï¾Œ", "Master Ace Surf"],
    ["ï¾ï¾—ï½²", "Mirai"],
    ["ï¾—ï½¯ï½¼ï½­", "Rush"],
    ["ï¾—ï½²ï¾„ï½´ï½°ï½½ï¾„ï¾—ï½¯ï½¸", "Light ace truck"],
    ["ï¾—ï½²ï¾„ï½´ï½°ï½½ï¾‰ï½±", "Light Ace Noah"],
    ["ï¾—ï½²ï¾„ï½´ï½°ï½½ï¾Šï¾žï¾", "Light Ace Bun"],
    ["ï¾—ï½²ï¾„ï½´ï½°ï½½ï¾œï½ºï¾žï¾", "Light ace wagon"],
    ["ï¾—ï½³ï¾‘", "Raum"],
    ["ï¾—ï½¸ï¾ƒï½¨ï½½", "Ractis"],
    ["ï¾—ï¾ï¾„ï¾žï½¸ï¾™ï½°ï½»ï¾žï½°", "Land Cruiser"],
    ["ï¾—ï¾ï¾„ï¾žï½¸ï¾™ï½°ï½»ï¾žï½°ï¾Œï¾Ÿï¾—ï¾„ï¾ž", "Land Cruiser Prado"],
    ["ï¾—ï¾ï¾„ï¾žï½¸ï¾™ï½°ï½»ï¾žï½°ï¾œï½ºï¾žï¾", "Land Cruiser Wagon"],
    ["ï¾™ï½°ï¾ï½°", "Rumi"],
    ["ï¾šï½¸ï½»ï½½", "Lexus"],
    ["ï¾šï½¼ï¾žï½±ï½½ï½´ï½°ï½½ï½ºï¾ï½­ï½°ï¾€", "Regius Ace commuter"],
    ["ï¾šï½¼ï¾žï½±ï½½ï½´ï½°ï½½ï¾Šï¾žï¾", "Regius Ace Bun"],
    ["ï¾šï½¼ï¾žï½±ï½½ï¾Šï¾žï¾", "Regius van"],
    ["ï½±ï¾„ï¾—ï½½", "Atlas"],
    ["ï½±ï¾ï¾žï¾†ï½°ï¾™ï½¶ï½°ï½ºï¾ž", "Avenir Cargo"],
    ["ï½±ï¾ï¾žï¾†ï½°ï¾™ï¾œï½ºï¾žï¾", "Avenir Wagon"],
    ["ï½²ï¾ï¾Œï½¨ï¾†ï¾ƒï½¨", "Infinity"],
    ["ï½³ï½¨ï¾ï½¸ï¾žï¾›ï½°ï¾„ï¾ž", "Wing Road"],
    ["ï½´ï½·ï½½ï¾Šï¾Ÿï½°ï¾„", "Expert"],
    ["ï½´ï½¸ï½½ï¾„ï¾šï½²ï¾™", "X-TRAIL"],
    ["ï½´ï½½ï½¶ï¾™ï½ºï¾ž", "Escargot"],
    ["ï½´ï¾™ï½¸ï¾žï¾—ï¾ï¾„ï¾ž", "Elgrand"],
    ["ï½µï½¯ï¾ƒï½¨", "Otiti"],
    ["ï½µï½°ï½½ï¾€ï½°", "Auster"],
    ["ï½·ï½¬ï¾Œï¾žï½µï½°ï¾™", "Cab-ol"],
    ["ï½·ï½¬ï¾—ï¾Šï¾žï¾", "Caravan"],
    ["ï½·ï½¬ï¾—ï¾Šï¾žï¾ï½ºï½°ï¾", "Caravan coach"],
    ["ï½·ï½¬ï¾—ï¾Šï¾žï¾ï¾Šï¾žï½½", "Caravan bus"],
    ["ï½·ï½­ï½°ï¾Œï¾ž", "Cube"],
    ["ï½·ï½­ï½°ï¾Œï¾žï½·ï½­ï½°ï¾‹ï¾žï½¯ï½¸", "Cube cubic"],
    ["ï½·ï½¯ï½¸ï½½", "Kicks"],
    ["ï½¸ï½µï¾", "Kuon"],
    ["ï½¸ï¾˜ï½¯ï¾Šï¾Ÿï½°ï¾„ï¾—ï½¯ï½¸", "Clipper truck"],
    ["ï½¸ï¾˜ï½¯ï¾Šï¾Ÿï½°ï¾Šï¾žï¾", "Clipper van"],
    ["ï½¸ï¾˜ï½¯ï¾Šï¾Ÿï½°ï¾˜ï½µ", "Clipper Rio"],
    ["ï½¸ï¾˜ï½¯ï¾Šï¾Ÿï½°", "Clipper"],

    ["ï½¸ï¾™ï½°", "Crew"],
    ["ï½¸ï¾žï¾›ï¾˜ï½±", "Gloria"],
    ["ï½¸ï¾žï¾›ï¾˜ï½±ï¾Šï¾žï¾", "Gloria van"],
    ["ï½¸ï¾žï¾›ï¾˜ï½±ï¾œï½ºï¾žï¾", "Gloria wagon"],
    ["ï½ºï¾ï¾„ï¾žï¾™", "Condor"],
    ["ï½»ï¾†ï½°", "Sunny"],
    ["ï½»ï¾†ï½°ï½¶ï¾˜ï¾Œï½«ï¾™ï¾†ï½±", "Sunny California"],
    ["ï½»ï¾†ï½°ï¾„ï¾—ï½¯ï½¸", "Sunny truck"],
    ["ï½»ï¾Œï½§ï¾˜", "Safari"],
    ["ï½»ï¾Œï½§ï¾˜ï¾„ï¾—ï½¯ï½¸", "Safari truck"],
    ["ï½»ï¾Œï½§ï¾˜ï¾Šï¾žï¾", "Safari vans"],
    ["ï½¼ï½°ï¾", "Cima"],
    ["ï½¼ï¾‹ï¾žï¾˜ï½±ï¾", "Civilian"],
    ["ï½¼ï¾™ï¾‹ï¾žï½±", "Sylvia"],
    ["ï½¼ï¾žï½­ï½°ï½¸", "Juke"],
    ["ï½½ï½¶ï½²ï¾—ï½²ï¾", "Skyline"],
    ["ï½½ï½¶ï½²ï¾—ï½²ï¾ ï½¸ï¾›ï½½ï½µï½°ï¾Šï¾žï½°", "Skyline crossover"],
    ["ï½½ï½¶ï½²ï¾—ï½²ï¾ï½¸ï½°ï¾ï¾Ÿ", "Skyline Coupe"],
    ["ï½½ï¾€ï¾ï½»ï¾ž", "Stanza"],
    ["ï½½ï¾ƒï½°ï½¼ï¾žï½±", "Stagea"],
    ["ï½¾ï¾„ï¾žï¾˜ï½¯ï½¸", "Cedric"],
    ["ï½¾ï¾„ï¾žï¾˜ï½¯ï½¸ï¾Šï¾žï¾", "Cedric van"],
    ["ï½¾ï¾„ï¾žï¾˜ï½¯ï½¸ï¾œï½ºï¾žï¾", "Cedric wagon"],
    ["ï½¾ï¾Œï½¨ï½°ï¾›", "Cefiro"],
    ["ï½¾ï¾Œï½¨ï½°ï¾›ï¾œï½ºï¾žï¾", "Cefiro Wagon"],
    ["ï½¾ï¾šï¾…", "Serena"],
    ["ï½¾ï¾šï¾…ï½¶ï½°ï½ºï¾ž", "Serenakago"],
    ["ï¾€ï¾žï½¯ï¾„ï½»ï¾", "Datsun"],
    ["ï¾€ï¾žï½¯ï¾„ï½»ï¾ï¾‹ï¾Ÿï½¯ï½¸ï½±ï½¯ï¾Œï¾Ÿ", "Datsun pickup"],
    ["ï¾ƒï½¨ï½°ï¾€ï¾ž", "Tiida"],
    ["ï¾ƒï½¨ï½°ï¾€ï¾žï¾—ï¾ƒï½¨ï½µ", "Tida Latio"],
    ["ï¾ƒï½¨ï½°ï¾‰", "Tino"],
    ["ï¾ƒï½¨ï½±ï¾…", "Teana"],
    ["ï¾ƒï¾—ï¾‰", "Terrano"],
    ["ï¾ƒï¾—ï¾‰ï¾šï½¸ï¾žï¾—ï½½", "Terranregulus"],
    ["ï¾ƒï¾žï½­ï½±ï¾˜ï½½", "Dualis"],
    ["ï¾ƒï¾žï½²ï½½ï¾ž", "Days"],
    ["ï¾ƒï¾žï½²ï½½ï¾žï¾™ï½°ï½¸ï½½", "Dayslakes"],
    ["ï¾†ï½¯ï½»ï¾", "Nissan"],
    ["ï¾†ï½¯ï½»ï¾ï¾„ï¾—ï½¯ï½¸", "Nissan truck"],
    ["ï¾†ï½¯ï½»ï¾ï¾Šï¾žï½½", "Nissan bus"],
    ["ï¾†ï½¯ï½»ï¾ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Nissan Forklift"],
    ["ï¾‰ï½°ï¾„", "Notes"],
    ["ï¾Šï¾žï½»ï¾—", "Basara"],
    ["ï¾Šï¾žï¾ˆï½¯ï¾„ï¾„ï¾—ï½¯ï½¸", "Banett truck"],
    ["ï¾Šï¾žï¾ˆï½¯ï¾„ï¾Šï¾žï¾", "Banet van"],
    ["ï¾Šï¾Ÿï½µ", "Pao"],
    ["ï¾Šï¾Ÿï¾™ï½»ï½°", "Pulsar"],
    ["ï¾Šï¾Ÿï¾™ï½»ï½°ï½¾ï¾˜ï½´", "Pulsar Serie"],
    ["ï¾‹ï¾žï½¯ï½¸ï½»ï¾‘", "Bixom"],
    ["ï¾‹ï¾Ÿï¾‰", "Pino"],
    ["ï¾Œï½¨ï½¶ï¾žï¾›", "Figaro"],
    ["ï¾Œï½ªï½±ï¾šï¾ƒï¾žï½¨", "Fair lady"],
    ["ï¾Œï½ªï½±ï¾šï¾ƒï¾žï½¨Z", "Fairlady Z"],
    ["ï¾Œï½°ï½¶ï¾ž", "Fugue"],
    ["ï¾Œï¾žï¾™ï½°ï¾Šï¾žï½°ï¾„ï¾ž", "Bluebird"],
    ["ï¾Œï¾žï¾™ï½°ï¾Šï¾žï½°ï¾„ï¾žï½¼ï¾™ï¾Œï½¨", "Bluebird Silphy"],
    ["ï¾Œï¾Ÿï¾˜ï¾’ï½°ï¾—", "Primera"],
    ["ï¾Œï¾Ÿï¾˜ï¾’ï½°ï¾—ï½¶ï¾ï¾‰", "Primera Camino"],
    ["ï¾Œï¾Ÿï¾˜ï¾’ï½°ï¾—ï½¶ï¾ï¾‰ï¾œï½ºï¾žï¾", "Primera Camino wagon"],
    ["ï¾Œï¾Ÿï¾˜ï¾’ï½°ï¾—ï¾œï½ºï¾žï¾", "Primera Wagon"],
    ["ï¾Œï¾Ÿï¾šï½°ï¾˜ï½°", "Prairie"],
    ["ï¾Œï¾Ÿï¾šï½»ï½°ï½¼ï¾žï½­", "Presage"],
    ["ï¾Œï¾Ÿï¾šï½¼ï¾žï¾ƒï¾žï¾ï¾„", "President"],
    ["ï¾Œï¾Ÿï¾šï½¾ï½±", "Presea"],
    ["ï¾Žï½°ï¾ï½°ï½ºï½°ï¾", "Homy coach"],
    ["ï¾Žï½°ï¾ï½°ï¾Šï¾žï¾", "Ho me van"],
    ["ï¾ï½°ï¾", "March"],
    ["ï¾ï½²ï½¸ï¾—", "Micra"],
    ["ï¾ï½·ï½¼ï¾", "Maxima"],
    ["ï¾ï½½ï¾„ï¾—ï¾™", "Mistral"],
    ["ï¾‘ï¾—ï½°ï¾‰", "Murano"],
    ["ï¾“ï½º", "Moko"],
    ["ï¾—ï½¼ï½°ï¾", "Racine"],
    ["ï¾—ï¾ƒï½¨ï½µ", "Latio"],
    ["ï¾—ï¾Œï½ªï½½ï¾€", "Lafesta"],
    ["ï¾—ï¾™ï½ºï¾ž", "Largo"],
    ["ï¾˜ï½°ï¾Œ", "Reef"],
    ["ï¾˜ï¾Šï¾žï¾ƒï½¨", "Liberty"],
    ["ï¾™ï½°ï½¸ï½½", "Rooks"],
    ["ï¾™ï½·ï¾‰", "Lukino"],
    ["ï¾™ï¾ˆï½¯ï½»", "Renaissa"],
    ["ï¾šï¾Šï¾Ÿï½°ï¾„ï¾ž", "Leopard"],
    ["ï¾šï¾Šï¾Ÿï½°ï¾„ï¾žJ.ï¾Œï½ªï¾˜ï½°", "Leppard J. Ferry"],
    ["ï¾›ï½°ï¾šï¾™", "Laurel"],
    ["ï¾ƒï¾žï¾™ï½¿ï¾™", "Delsol"],

    ["ï½½ï¾—ï½¯ï½¼ï½­", "Slash"],
    ["ï¾Œï¾Ÿï¾—ï½½", "Plus"],

    ["ï½±ï½³ï¾žï½§ï¾ï½¼ï½±", "Avancia"],
    ["ï½±ï½¸ï¾ƒï½¨ï½½ï¾„ï¾˜ï½°ï¾„", "Acty Street"],
    ["ï½±ï½¸ï¾ƒï½¨ï¾„ï¾—ï½¯ï½¸", "Acty truck"],
    ["ï½±ï½¸ï¾ƒï½¨ï¾Šï¾žï¾", "Activan"],
    ["ï½±ï½ºï½°ï¾„ï¾ž", "Accord"],
    ["ï½¸ï½°ï¾ï¾Ÿ", "Coupe"],

    ["ï½±ï½½ï½ºï½¯ï¾„", "Ascot"],
    ["ï½²ï¾ï½»ï½²ï¾„", "Insight"],
    ["ï½²ï¾ï½½ï¾Šï¾Ÿï½²ï½±", "Inspire"],
    ["ï½²ï¾ï¾ƒï½¸ï¾žï¾—", "Integra"],
    ["ï½³ï¾žï½ªï½¾ï¾žï¾™", "Wesel"],
    ["ï½´ï½±ï½³ï½ªï½²ï¾Œï¾ž", "Airwave"],
    ["ï½´ï¾ƒï¾žï½¨ï½¯ï½¸ï½½", "Edix"],
    ["ï½´ï¾˜ï½¼ï½µï¾", "Elysion"],
    ["ï½´ï¾šï¾’ï¾ï¾„", "Element"],
    ["ï½µï¾ƒï¾žï½¯ï½¾ï½²", "Odyssey"],
    ["ï½µï¾™ï¾ƒï½¨ï½±", "Ortia"],
    ["ï½·ï½¬ï¾Šï¾Ÿ", "Capacity"],
    ["ï½¸ï¾›ï½½ï¾›ï½°ï¾„ï¾ž", "Crossroad"],
    ["ï½¸ï¾žï¾šï½²ï½½", "Grace"],
    ["ï½ºï¾ï¾ï½ªï¾™ï¾„", "Concerto"],
    ["ï½»ï¾žï½¯ï¾‚", "Thats"],
    ["ï½¼ï½¬ï¾„ï¾™", "Shuttle"],
    ["ï½¼ï¾ƒï½¨", "City"],
    ["ï½¼ï¾‹ï¾žï½¯ï½¸", "Civic"],

    ["ï½¼ï½¬ï¾„ï¾™", "shuttle"],
    ["ï¾Œï½ªï¾˜ï½µ", "Ferio"],

    ["ï½¼ï¾žï½ªï½²ï¾„ï¾ž", "Jade"],
    ["ï½½ï¾ƒï½¯ï¾Œï¾Ÿï¾œï½ºï¾žï¾", "Step Wagon"],
    ["ï½½ï¾„ï¾˜ï½°ï¾‘", "Stream"],
    ["ï½½ï¾Šï¾Ÿï½²ï½¸", "Spike"],
    ["ï½¾ï½²ï¾Šï¾žï½°", "Saber"],
    ["ï½¾ï¾žï½½ï¾„", "Zest"],
    ["ï¾„ï½©ï¾ƒï¾žï½²", "Today"],
    ["ï¾„ï½©ï¾ƒï¾žï½² ï½±ï½¿ï½¼ï½´", "Today Associe"],
    ["ï¾„ï½©ï¾ƒï¾žï½²ï¾Šï¾žï¾", "Today Van"],
    ["ï¾„ï¾™ï¾ˆï½µ", "Torneo"],
    ["ï¾„ï¾žï¾ï½°ï¾†", "Domani"],
    ["ï¾Šï¾žï¾“ï½½", "Vamos"],
    ["ï¾Šï¾Ÿï½°ï¾„ï¾…ï½°", "Partner"],
    ["ï¾‹ï¾žï½°ï¾„", "Beat"],
    ["ï¾‹ï¾žï½¶ï¾žï½°", "Bigger"],
    ["ï¾Œï½¨ï½¯ï¾„", "Fit"],
    ["ï¾Œï½¨ï½¯ï¾„ ï½¼ï½¬ï¾„ï¾™", "Fit shuttle"],
    ["ï¾Œï¾˜ï½°ï¾„ï¾ž", "Fried"],
    ["ï¾Œï¾˜ï½°ï¾„ï¾žï½½ï¾Šï¾Ÿï½²ï½¸", "Fried spike"],
    ["ï¾Œï¾Ÿï¾šï¾˜ï½­ï½°ï¾„ï¾ž", "Prelude"],
    ["ï¾Žï¾—ï½²ï½¿ï¾žï¾", "Horizon"],
    ["ï¾Žï¾ï¾€ï¾ž", "Honda"],
    ["ï¾“ï¾‹ï¾žï¾˜ï½µ", "Mobilio"],
    ["ï¾—ï½²ï¾Œ", "Life"],
    ["ï¾—ï½²ï¾Œï¾€ï¾žï¾ï½¸", "Life Dunk"],
    ["ï¾—ï½¸ï¾žï¾šï½²ï¾„", "Lagret"],
    ["ï¾—ï¾Œï½§ï½°ï½¶ï¾ž", "Rafaga"],
    ["ï¾šï½¼ï¾žï½ªï¾ï¾„ï¾ž", "Legend"],
    ["ï¾›ï½ºï¾ž", "Logo"],

    ["ekï½±ï½¸ï¾ƒï½¨ï¾Œï¾ž", "ek active"],
    ["ekï½¶ï½½ï¾€ï¾‘", "ek Custom"],
    ["ekï½¸ï¾—ï½¯ï½¼ï½¨", "ek classy"],
    ["ekï½½ï¾ï¾Ÿï½°ï½½", "ek space"],
    ["ekï½½ï¾Žï¾Ÿï½°ï¾‚", "ek Sports"],
    ["ekï¾œï½ºï¾žï¾", "ek Wagon"],

    ["ï½±ï½³ï¾„ï¾—ï¾ï¾€ï¾žï½°", "Outlander"],
    ["ï½±ï½³ï¾„ï¾—ï¾ï¾€ï¾žï½°PHEV", "Outlander PHEV"],
    ["ï½±ï½½ï¾Šï¾Ÿï½²ï½±", "Aspire"],
    ["ï½´ï½±ï¾„ï¾šï½¯ï½¸", "Air Trek"],
    ["ï½´ï½±ï¾›ï½¸ï½²ï½°ï¾", "Aero Queen"],
    ["ï½´ï½±ï¾›ï½½ï¾€ï½°", "Aerostar"],
    ["ï½´ï½±ï¾›ï¾ï¾ƒï¾žï½¨", "Aeromidi"],
    ["ï½´ï½¸ï¾˜ï¾Œï¾Ÿï½½", "Eclipse"],
    ["ï½¶ï¾˜ï½½ï¾", "Charisma"],
    ["ï½·ï½¬ï¾ï¾€ï½°", "CANTER"],
    ["ï½·ï½¬ï¾ï¾€ï½°ï½¶ï¾žï½¯ï¾‚", "Cantar Guts"],
    ["ï½·ï¾žï½¬ï¾—ï¾", "Galant"],
    ["ï½·ï¾žï½¬ï¾—ï¾ï¾Œï½«ï¾™ï¾ƒï½¨ï½½", "Galant Fortis"],
    ["ï½¸ï¾žï¾—ï¾ï¾ƒï¾žï½¨ï½½", "Grandis"],
    ["ï½¸ï¾žï¾šï½°ï¾„", "Great"],
    ["ï½ºï¾™ï¾„", "Colt"],
    ["ï½ºï¾™ï¾„ï¾Œï¾Ÿï¾—ï½½", "Colt Plus"],
    ["ï½¼ï½¬ï¾˜ï½µ", "Chariot"],
    ["ï½¼ï½¬ï¾˜ï½µï½¸ï¾žï¾—ï¾ï¾ƒï¾žï½¨ï½½", "Chariot Grandis"],
    ["ï½¼ï½¸ï¾žï¾", "Sigma"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿ", "Jeep"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°ï½¸ï¾žï¾šï½°ï¾„", "Super Great"],
    ["ï½½ï¾„ï¾—ï½°ï¾€ï¾ž", "Strada"],
    ["ï¾€ï½³ï¾ï¾Žï¾žï½¯ï½¸ï½½", "Town box"],
    ["ï¾€ï½³ï¾ï¾Žï¾žï½¯ï½¸ï½½ï¾œï½²ï¾„ï¾ž", "Town Box Wide"],
    ["ï¾ï½¬ï¾šï¾ï½¼ï¾žï½¬ï½°", "Challenger"],
    ["ï¾ƒï¾žï½¨ï½±ï¾ï¾ï¾ƒ", "Diamante"],
    ["ï¾ƒï¾žï½¨ï½±ï¾ï¾ï¾ƒï¾œï½ºï¾žï¾", "Diamante Wagon"],
    ["ï¾ƒï¾žï½¨ï½µï¾", "Dion"],
    ["ï¾ƒï¾žï½¨ï¾ï½ºï¾ž", "Dingo"],
    ["ï¾ƒï¾žï¾Žï¾žï¾ˆï½±", "Debonair"],
    ["ï¾ƒï¾žï¾˜ï½¶D2", "Delica D2"],
    ["ï¾ƒï¾žï¾˜ï½¶D3", "Delica D3"],
    ["ï¾ƒï¾žï¾˜ï½¶D5", "Delica D5"],
    ["ï¾ƒï¾žï¾˜ï½¶ï½½ï¾ï¾Ÿï½°ï½½ï½·ï¾žï½±", "Delica Space Gear"],
    ["ï¾ƒï¾žï¾˜ï½¶ï¾„ï¾—ï½¯ï½¸", "Delica truck"],
    ["ï¾ƒï¾žï¾˜ï½¶ï¾Šï¾žï¾", "Delicatan"],
    ["ï¾ƒï¾žï¾˜ï½¶ï¾œï½ºï¾žï¾", "Delica wagon"],
    ["ï¾„ï½¯ï¾Žï¾Ÿ", "Toppo"],
    ["ï¾„ï½¯ï¾Žï¾ŸBJ", "Toppo BJ"],
    ["ï¾„ï½¯ï¾Žï¾ŸBJï¾Šï¾žï¾", "Toppo BJ van"],
    ["ï¾„ï½¯ï¾Žï¾ŸBJï¾œï½²ï¾„ï¾ž", "Toppo BJ Wide"],
    ["ï¾„ï¾—ï½²ï¾„ï¾", "Triton"],
    ["ï¾Šï¾Ÿï½¼ï¾žï½ªï¾›", "Pajero"],
    ["ï¾Šï¾Ÿï½¼ï¾žï½ªï¾›ï½²ï½µ", "Pajeroio"],
    ["ï¾Šï¾Ÿï½¼ï¾žï½ªï¾›ï½¼ï¾žï½­ï¾†ï½±", "Pajero Jr."],
    ["ï¾Šï¾Ÿï½¼ï¾žï½ªï¾›ï¾ï¾†", "Pajero Mini"],
    ["ï¾Œï½¿ï½³ï¾„ï¾—ï½¯ï½¸", "Fuso Truck"],
    ["ï¾Œï½¿ï½³ï¾Šï¾žï½½", "Fuso bus"],
    ["ï¾Œï½¿ï½³ï¾Œï½§ï½²ï¾€ï½°", "Futou Fighter"],
    ["ï¾Œï¾Ÿï¾—ï½³ï¾ƒï¾žï½¨ï½±", "Plundia"],
    ["ï¾ï¾‚ï¾‹ï¾žï½¼", "Mitsubishi"],
    ["ï¾ï¾‚ï¾‹ï¾žï½¼ï¾Šï¾žï½½", "Mitsubishi bus"],
    ["ï¾ï¾‚ï¾‹ï¾žï½¼ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Mitsubishi forklift"],
    ["ï¾ï¾‚ï¾‹ï¾žï½¼ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Mitsubishi wheel loader"],
    ["ï¾ï¾‚ï¾‹ï¾žï½¼ï¾•ï¾ï¾Žï¾ž", "Mitsubishi Yumbo"],
    ["ï¾ï¾†ï½¶", "Minica"],
    ["ï¾ï¾†ï½¶ï¾„ï½¯ï¾Žï¾Ÿ", "Minicattoppo"],
    ["ï¾ï¾†ï½¶ï¾„ï½¯ï¾Žï¾Ÿï¾Šï¾žï¾", "Mini Katotoban"],
    ["ï¾ï¾†ï½¶ï¾Šï¾žï¾", "Minicabban"],
    ["ï¾ï¾†ï½·ï½¬ï¾Œï¾žï¾„ï¾—ï½¯ï½¸", "Minicab truck"],
    ["ï¾ï¾†ï½·ï½¬ï¾Œï¾žï¾Šï¾žï¾", "Mini Cab Van"],
    ["ï¾ï¾†ï½·ï½¬ï¾Œï¾žï¾ï½°ï¾Œï¾ž", "Minicab Meeve"],
    ["ï¾ï¾†ï¾–ï¾", "Mignon"],
    ["ï¾ï¾—ï½°ï½¼ï¾žï½­", "Mirage"],
    ["ï¾ï¾—ï½°ï½¼ï¾žï½­ï½±ï½½ï¾ƒï½¨", "Mirage Asti"],
    ["ï¾—ï¾ï½»ï½°", "Lancer"],
    ["ï¾—ï¾ï½»ï½°ï½¾ï¾ƒï¾žï½¨ï½±", "Lancer Cedia"],
    ["ï¾—ï¾ï½»ï½°ï½¾ï¾ƒï¾žï½¨ï½±ï¾œï½ºï¾žï¾", "Lancer Cedia Wagon"],
    ["ï¾—ï¾ï½»ï½°ï¾Šï¾žï¾", "Lancer Bun"],
    ["ï¾—ï¾ï½»ï½°ï¾œï½ºï¾žï¾", "Lancer Wagon"],
    ["ï¾˜ï¾ï¾žï¾›", "Libero"],
    ["ï¾˜ï¾ï¾žï¾›ï½¶ï½°ï½ºï¾ž", "Liberokago"],
    ["ï¾šï½¸ï¾žï¾…ï¾‘", "Regnum"],
    ["ï¾›ï½°ï½»ï¾ž", "Rosa"],
    ["ï½±ï½¸ï½¾ï¾—", "Axela"],
    ["ï½±ï¾ƒï¾ï½»ï¾žï½½ï¾Žï¾Ÿï½°ï¾‚", "Atenza sports"],
    ["ï½±ï¾ƒï¾ï½»ï¾žï½¾ï¾€ï¾žï¾", "Atenza sedan"],
    ["ï½±ï¾ƒï¾ï½»ï¾žï¾œï½ºï¾žï¾", "Atenza Wagon"],
    ["ï½¶ï¾ï¾Ÿï¾—", "Capella"],
    ["ï½¶ï¾ï¾Ÿï¾—ï¾œï½ºï¾žï¾", "Capella wagon"],
    ["ï½·ï½¬ï¾›ï¾™", "Carol"],
    ["ï½¸ï¾›ï¾‰ï½½", "Cronos"],
    ["ï½½ï½¸ï¾—ï¾‘ï¾„ï¾—ï½¯ï½¸", "Scrum truck"],
    ["ï½½ï½¸ï¾—ï¾‘ï¾Šï¾žï¾", "Scrum van"],
    ["ï½½ï½¸ï¾—ï¾‘ï¾œï½ºï¾žï¾", "Scrum wagon"],
    ["ï½½ï¾‹ï¾Ÿï½±ï½°ï¾‰", "Spiano"],
    ["ï½¾ï¾ï¾ƒï½¨ï½±", "Sentia"],
    ["ï¾€ï½²ï¾€ï¾", "Titan"],
    ["ï¾ƒï¾žï¾ï½µ", "Demio"],
    ["ï¾„ï¾˜ï¾‹ï¾žï½­ï½°ï¾„", "Tribute"],
    ["ï¾‹ï¾žï½±ï¾ï¾ƒ", "Biante"],
    ["ï¾Œï½§ï¾ï¾˜ï½±", "Familia"],
    ["ï¾Œï½§ï¾ï¾˜ï½±S-ï¾œï½ºï¾žï¾", "Familia S - Wagon"],
    ["ï¾Œï½§ï¾ï¾˜ï½±ï¾Šï¾žï¾", "Familia van"],
    ["ï¾Œï½§ï¾ï¾˜ï½±ï¾œï½ºï¾žï¾", "Familia wagon"],
    ["ï¾Œï¾šï½±", "Flare"],
    ["ï¾Œï¾šï½±ï¾œï½ºï¾žï¾", "Flare wagon"],
    ["ï¾Œï¾Ÿï¾šï¾ï½¼ï½°", "Premacy"],
    ["ï¾Œï¾Ÿï¾›ï½¼ï½°ï¾„ï¾ž", "Procede"],
    ["ï¾Œï¾Ÿï¾›ï½¼ï½°ï¾„ï¾žï¾ï½°ï¾‹ï¾žï½°", "Proseed Marby"],
    ["ï¾Œï¾Ÿï¾›ï½¼ï½°ï¾„ï¾žï¾šï¾Šï¾žï¾ï¾ƒ", "Procede Levante"],
    ["ï¾ï¾žï¾˜ï½°ï½»", "Verisa"],
    ["ï¾ï¾Ÿï¾™ï½¿ï¾…", "Persona"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾„ï¾—ï½¯ï½¸", "Bongo Truck"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Šï¾žï¾", "Bongo van"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Œï¾šï¾ï¾ƒï¾žï½¨", "Bongo Frendy"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Œï¾šï¾ï¾ƒï¾žï½¨ AFT", "Bongo Friendy AFT"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Œï¾žï¾›ï½°ï¾†ï½¨ï¾„ï¾—ï½¯ï½¸", "Bongo Bronny truck"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Œï¾žï¾›ï½°ï¾†ï½¨ï¾Šï¾žï¾", "Bongo Bronny van"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾Œï¾žï¾›ï½°ï¾†ï½¨ï¾œï½ºï¾žï¾", "Bongo Bronny Wagon"],
    ["ï¾Žï¾žï¾ï½ºï¾žï¾œï½ºï¾žï¾", "Bongo Wagon"],
    ["ï¾Žï¾Ÿï½°ï¾€ï½°ï½·ï½¬ï¾Œï¾ž", "Porter cab"],
    ["ï¾ï¾‚ï¾€ï¾ž", "Mazda"],
    ["ï¾ï¾šï½°ï¾†ï½±", "Milania"],
    ["ï¾•ï½°ï¾‰ï½½500", "Eunos 500"],
    ["ï¾•ï½°ï¾‰ï½½800", "Eunos 800"],
    ["ï¾•ï½°ï¾‰ï½½ï½ºï½½ï¾“", "Eunos Cosmo"],
    ["ï¾•ï½°ï¾‰ï½½ï¾Œï¾Ÿï¾šï½¯ï½¿", "Eunos Presso"],
    ["ï¾—ï¾‹ï¾Ÿï½­ï¾€", "Laputa"],
    ["ï¾—ï¾ï¾ƒï½¨ï½½", "Lantis"],
    ["ï¾™ï½°ï¾ï½ª", "Luce"],
    ["ï¾šï¾‹ï¾žï½­ï½°", "Review"],
    ["ï¾›ï½°ï¾„ï¾žï½½ï¾€ï½°", "Roadster"],

    ["MRï¾œï½ºï¾žï¾", "MR Wagon"],
    ["SX4", "SX 4"],
    ["ï½±ï¾™ï¾„", "Alto"],
    ["ï½±ï¾™ï¾„ï½´ï½º", "Alto Eco"],
    ["ï½±ï¾™ï¾„ï¾Šï¾žï¾", "Altoban"],
    ["ï½±ï¾™ï¾„ï¾—ï¾Šï¾Ÿï¾", "Altra Pan"],
    ["ï½±ï¾™ï¾„ï¾œï½°ï½¸ï½½", "Alto Works"],
    ["ï½²ï½¸ï¾žï¾†ï½½", "Ignis"],
    ["ï½´ï½½ï½¸ï½°ï¾„ï¾ž", "Escudo"],
    ["ï½´ï½½ï½¸ï½°ï¾„ï¾žï¾‰ï¾ï¾„ï¾ž", "Escudo Nomad"],
    ["ï½´ï¾Œï¾žï¾˜ï½¨", "Every"],
    ["ï½´ï¾Œï¾žï¾˜ï½¨ï¾Œï¾Ÿï¾—ï½½", "Every Plus"],
    ["ï½´ï¾Œï¾žï¾˜ï½¨ï¾—ï¾ï¾ƒï¾žï½¨", "Every Randy"],
    ["ï½´ï¾Œï¾žï¾˜ï½¨ï¾œï½ºï¾žï¾", "Every Wagon"],
    ["ï½´ï¾˜ï½µ", "Elio"],
    ["ï½¶ï¾Œï¾Ÿï¾ï½°ï¾‰", "Cappuccino"],
    ["ï½¶ï¾™ï¾€ï½½", "Cartas"],
    ["ï½¶ï¾™ï¾€ï½½ï½¸ï¾šï½¾ï¾ï¾„", "Cartast Crescent"],
    ["ï½¶ï¾™ï¾€ï½½ï½¸ï¾šï½¾ï¾ï¾„ï¾œï½ºï¾žï¾", "Cartast Crescent Wagon"],
    ["ï½·ï½¬ï¾—", "Character"],
    ["ï½·ï½¬ï¾˜ï½°ï¾Šï¾žï¾", "Carry van"],
    ["ï½·ï½¬ï¾˜ï½²ï¾„ï¾—ï½¯ï½¸", "Carry truck"],
    ["ï½·ï½»ï¾žï½¼", "Kizashi"],
    ["ï½¸ï¾žï¾—ï¾ï¾„ï¾žï½´ï½½ï½¸ï½°ï¾„ï¾ž", "Grand Escudo"],
    ["ï½¼ï¾Žï¾žï¾šï½°MW", "Chevrolet MW"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¸ï¾™ï½°ï½½ï¾ž", "Chevrolet cruise"],
    ["ï½¼ï¾žï¾‘ï¾†ï½°", "Jimny"],
    ["ï½¼ï¾žï¾‘ï¾†ï½°ï½¼ï½´ï¾—", "Jimny Sierra"],
    ["ï½¼ï¾žï¾‘ï¾†ï½°ï¾œï½²ï¾„ï¾ž", "Jimny Wide"],
    ["ï½½ï½²ï¾Œï¾„", "Swift"],
    ["ï½½ï½½ï¾žï½·", "Suzuki"],
    ["ï½½ï¾Œï¾Ÿï¾—ï½¯ï½¼ï½­", "Splash"],
    ["ï½½ï¾ï¾Ÿï½°ï½¼ï½±", "Spacia"],
    ["ï½¾ï¾†ï½±ï½¶ï½°", "Senior car"],
    ["ï½¾ï¾™ï¾Žï¾ž", "Cervo"],
    ["ï½¾ï¾™ï¾Žï¾žï¾“ï½°ï¾„ï¾ž", "Cervo mode"],
    ["ï½¿ï¾˜ï½µ", "Sorio"],
    ["ï¾‚ï½²ï¾", "Twin"],
    ["ï¾Šï½½ï¾—ï½°", "Hustler"],
    ["ï¾Šï¾žï¾šï½°ï¾‰", "Vareno"],
    ["ï¾Šï¾Ÿï¾šï½¯ï¾„", "Palette"],
    ["ï¾Šï¾Ÿï¾šï½¯ï¾„ SW", "Palette SW"],
    ["ï¾ï½²ï¾ƒï½¨ï¾Žï¾žï½°ï½²", "Mighty Boy"],
    ["ï¾—ï¾ï¾ƒï¾žï½¨", "Randy"],

    ["ï¾œï½ºï¾žï¾Rï½¿ï¾˜ï½µ", "Wagon R solio"],
    ["ï¾œï½ºï¾žï¾Rï¾Œï¾Ÿï¾—ï½½", "Wagon R Plus"],
    ["ï¾œï½ºï¾žï¾Rï¾œï½²ï¾„ï¾ž", "Wagon R Wide"],
    ["ï¾œï½ºï¾žï¾R", "Wagon R"],
    ["ï½±ï¾„ï¾šï½°7", "Atrai 7"],
    ["ï½±ï¾„ï¾šï½°ï¾Šï¾žï¾", "Atrai van"],
    ["ï½±ï¾„ï¾šï½°ï¾œï½ºï¾žï¾", "Atrai Wagon"],
    ["ï½±ï¾™ï¾ƒï½¨ï½½", "Artis"],
    ["ï½³ï½ªï½²ï½¸", "Wake"],
    ["ï½´ï½¯ï½¾", "Essay"],
    ["ï½µï¾Œï¾Ÿï¾ƒï½¨", "Opti"],
    ["ï½·ï½¬ï½½ï¾„", "Cast"],
    ["ï½¸ï½°", "Ku"],
    ["ï½ºï¾ï¾Ÿï¾", "Copen"],
    ["ï½»ï¾ï¾Šï¾žï½°ï¾„ï¾—ï½¯ï½¸", "Sambar truck"],
    ["ï½¼ï½¬ï¾šï½°ï¾„ï¾ž", "Chardy"],
    ["ï½½ï¾„ï½°ï¾˜ï½±", "Story"],
    ["ï½¿ï¾†ï½¶", "Sonica"],
    ["ï¾€ï¾Œï¾„", "Taft"],
    ["ï¾€ï¾ï¾„", "Tant"],
    ["ï¾€ï¾ï¾„ ï½´ï½¸ï¾žï½¾ï¾ž", "Tanto Exe"],
    ["ï¾€ï¾žï½²ï¾Šï¾‚", "Daihatsu"],
    ["ï¾ƒï¾˜ï½µï½½", "Terios"],
    ["ï¾ƒï¾˜ï½µï½½ï½·ï½¯ï¾„ï¾ž", "Terios Kid"],
    ["ï¾ƒï¾˜ï½µï½½ï¾™ï½·ï½±", "Terios Rukia"],
    ["ï¾ƒï¾žï¾™ï¾€ï¾„ï¾—ï½¯ï½¸", "Delta truck"],
    ["ï¾ƒï¾žï¾™ï¾€ï¾Šï¾žï¾", "Delta van"],
    ["ï¾ƒï¾žï¾™ï¾€ï¾œï½ºï¾žï¾", "Delta wagon"],
    ["ï¾„ï½°ï¾™", "Tall"],
    ["ï¾ˆï½²ï½·ï½¯ï¾„ï¾ž", "Naked"],
    ["ï¾Šï½²ï½¾ï¾žï½¯ï¾„ï½·ï½¬ï¾ƒï¾žï½¨ï½°", "Hijet Caddy"],
    ["ï¾Šï½²ï½¾ï¾žï½¯ï¾„ï¾„ï¾—ï½¯ï½¸", "Hijet truck"],
    ["ï¾Šï½²ï½¾ï¾žï½¯ï¾„ï¾Šï¾žï¾", "Hijet van"],
    ["ï¾Šï¾Ÿï½²ï½»ï¾žï½°", "Pizer"],
    ["ï¾‹ï¾žï½°ï½ºï¾ž", "Vigo"],
    ["ï¾Œï¾žï½°ï¾", "Boone"],
    ["ï¾ï½¾ï¾žï½¯ï¾„â…¡", "Midget â…¡"],
    ["ï¾ï¾—", "Mira"],
    ["ï¾ï¾— ï½²ï½°ï½½", "Mira ES"],
    ["ï¾ï¾— ï½ºï½ºï½±", "Mira cocoa"],
    ["ï¾ï¾—ï½±ï½³ï¾žï½¨", "Milaavi"],
    ["ï¾ï¾—ï½¼ï¾žï½°ï¾‰", "Mirasino"],
    ["ï¾ï¾—ï¾Šï¾žï¾", "Miraban"],
    ["ï¾‘ï½°ï½³ï¾ž", "Move"],
    ["ï¾‘ï½°ï½³ï¾ž ï¾—ï¾ƒ", "Move latte"],
    ["ï¾‘ï½°ï½³ï¾žï½·ï½¬ï¾ï¾Šï¾žï½½", "Move canvas"],
    ["ï¾‘ï½°ï½³ï¾žï½ºï¾ï¾ƒ", "Move Conte"],
    ["ï¾’ï¾‹ï¾žï½³ï½½", "Moebius"],
    ["ï¾—ï½¶ï¾žï½°", "A lager"],
    ["ï¾›ï½¯ï½·ï½°", "Rocky"],
    ["ï½±ï¾™ï½¼ï½µï½°ï¾ˆ", "Alcione"],
    ["ï½±ï¾™ï½¼ï½µï½°ï¾ˆSVX", "Alcione SVX"],
    ["ï½²ï¾ï¾Œï¾Ÿï¾šï½¯ï½»", "Impreza"],
    ["ï½²ï¾ï¾Œï¾Ÿï¾šï½¯ï½»G4", "Impreza G4"],
    ["ï½²ï¾ï¾Œï¾Ÿï¾šï½¯ï½»ï¾œï½ºï¾žï¾", "Impressa Wagon"],
    ["ï½³ï¾žï½¨ï½³ï¾žï½¨ï½µ", "Vivio"],
    ["ï½³ï¾žï½¨ï½³ï¾žï½¨ï½µ ï¾‹ï¾žï½½ï¾„ï¾›", "Vivio Bistro"],
    ["ï½³ï¾žï½¨ï½³ï¾žï½¨ï½µï¾Šï¾žï¾", "Vivio Ban"],
    ["ï½´ï½¸ï½¼ï½°ï½¶ï¾ž", "Exiga"],
    ["ï½»ï¾ï¾Šï¾žï½°ï¾ƒï¾žï½¨ï½±ï½½ï¾Šï¾žï¾", "Samba Diaz van"],
    ["ï½»ï¾ï¾Šï¾žï½°ï¾ƒï¾žï½¨ï½±ï½½ï¾œï½ºï¾žï¾", "Samba Diaz Wagon"],
    ["ï½»ï¾ï¾Šï¾žï½°ï¾Šï¾žï¾", "Sambar van"],
    ["ï½¼ï¾žï½¬ï½½ï¾ƒï½¨", "Justy"],
    ["ï½½ï¾ƒï¾—", "Stella"],
    ["ï½½ï¾Šï¾žï¾™", "Subaru"],
    ["ï½½ï¾Šï¾žï¾™360", "Subaru 360"],
    ["ï½½ï¾Šï¾žï¾™XV", "Subaru XV"],
    ["ï¾ƒï¾žï½¯ï½¸ï½½", "Dex"],
    ["ï¾„ï¾—ï½³ï¾žï½¨ï½¯ï½¸", "Travik"],
    ["ï¾„ï¾šï½¼ï¾žï½±", "Tresia"],
    ["ï¾„ï¾žï¾ï¾ï½ºï¾ž", "Domingo"],
    ["ï¾Œï½«ï¾šï½½ï¾€ï½°", "Forester"],
    ["ï¾Œï¾Ÿï¾šï½µ", "Pleo"],
    ["ï¾Œï¾Ÿï¾šï½µï¾ˆï½½ï¾€", "Pretonesta"],
    ["ï¾Œï¾Ÿï¾šï½µï¾Šï¾žï¾", "Pleovan"],
    ["ï¾Œï¾Ÿï¾šï½µï¾Œï¾Ÿï¾—ï½½", "Pleo Plus"],
    ["ï¾™ï½¸ï¾—", "Lukla"],
    ["ï¾šï½¯ï½¸ï½½", "Rex"],
    ["ï¾šï½³ï¾žï½«ï½°ï½¸ï¾ž", "Levog"],
    ["ï¾šï½¶ï¾žï½¼ï½¨", "Legacy"],
    ["ï¾šï½¶ï¾žï½¼ï½¨B4", "Legacy B 4"],
    ["ï¾šï½¶ï¾žï½¼ï½¨ï¾œï½ºï¾žï¾", "Legacy Wagon"],
    ["117ï½¸ï½°ï¾ï¾Ÿ", "117 Coupe"],
    ["ï½±ï½½ï½¶", "Aska"],
    ["ï½²ï½½ï½½ï¾ž", "Isuzu"],
    ["ï½²ï½½ï½½ï¾žï¾„ï¾—ï½¯ï½¸", "Isuzu truck"],
    ["ï½²ï½½ï½½ï¾žï¾Šï¾žï½½", "Isuzbas"],
    ["ï½³ï½¨ï½»ï¾žï½°ï¾„ï¾ž", "Wizard"],
    ["ï½´ï¾™ï¾Œ", "Elf"],
    ["ï½´ï¾™ï¾Œ150", "Elf 150"],
    ["ï½´ï¾™ï¾Œ250", "Elf 250"],
    ["ï½¶ï¾žï½°ï¾—", "Gala"],
    ["ï½¶ï¾žï½°ï¾—ï¾ï½µ", "Gharamio"],
    ["ï½·ï¾žï½¶ï¾ž", "Giga"],
    ["ï½ºï¾“", "Como"],
    ["ï½¼ï¾žï½ªï¾ï¾†", "Gemini"],
    ["ï½¼ï¾žï½¬ï½°ï¾†ï½°", "Journey"],
    ["ï½¼ï¾žï½¬ï½½ï¾„ï¾", "Juston"],
    ["ï¾‹ï¾žï½¯ï½¸ï¾žï¾Žï½°ï¾", "Big horn"],
    ["ï¾‹ï¾žï½°ï½¸ï¾›ï½½", "Beklos"],
    ["ï¾‹ï¾Ÿï½±ï½¯ï¾‚ï½±", "Piazza"],
    ["ï¾Œï½§ï½°ï½ºï¾žï¾„ï¾—ï½¯ï½¸", "Fargo truck"],
    ["ï¾Œï½§ï½°ï½ºï¾žï¾Šï¾žï¾", "Fargoban"],
    ["ï¾Œï½§ï½°ï½ºï¾žï¾Œï½¨ï¾˜ï½°", "Fargo Philly"],
    ["ï¾Œï½§ï½°ï½ºï¾žï¾œï½ºï¾žï¾", "Fargo Wagon"],
    ["ï¾Œï½«ï½½ï¾€ï½°ï¾›ï¾ƒï¾žï½µ", "Foster Rodeo"],
    ["ï¾Œï½«ï¾œï½°ï¾„ï¾ž", "Forward"],
    ["ï¾ï¾žï¾šï½¯ï¾„", "Beret"],
    ["ï¾ï½­ï½°", "Mu"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°ï¾„ï¾žï¾™ï¾Œï½¨ï¾", "Super Dolphin"],
    ["ï½¾ï¾šï½¶ï¾ž", "Selega"],
    ["ï¾„ï¾žï¾™ï¾Œï½¨ï¾", "Dolphin"],
    ["ï¾‹ï¾‰", "Hino"],
    ["ï¾‹ï¾‰FD", "Hino FD"],
    ["ï¾‹ï¾‰ï¾ƒï¾žï½­ï¾„ï¾›", "Hinodutro"],
    ["ï¾‹ï¾‰ï¾„ï¾—ï½¯ï½¸", "Hino truck"],
    ["ï¾‹ï¾‰ï¾Šï¾žï½½", "Hinoobasu"],
    ["ï¾‹ï¾‰ï¾˜ï½´ï½¯ï½¾", "Hinoriesse"],
    ["ï¾‹ï¾‰ï¾šï½²ï¾ï¾Žï¾žï½°", "Hino Rainbow"],
    ["ï¾‹ï¾‰ï¾šï¾ï½¼ï¾žï½¬ï½°", "Hino Ranger"],
    ["ï¾Œï¾žï¾™ï½°ï¾˜ï¾Žï¾žï¾", "Blue Ribbon"],
    ["ï¾Œï¾Ÿï¾›ï¾Œï½¨ï½±", "A profile"],
    ["ï¾’ï¾™ï¾Œï½§", "Melpha"],
    ["CATï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "CAT wheel loader"],
    ["TCMï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "TCM forklift"],
    ["TCMï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "TCM wheel loader"],
    ["ï½±ï½²ï¾", "Aichi"],
    ["ï½±ï¾ƒï½¯ï½¸ï½½", "Atex"],
    ["ï½±ï¾˜ï¾ï¾‚", "Arimitsu"],
    ["ï½²ï½¾ï½·", "Ise ki"],
    ["ï½²ï¾œï¾€", "Iwata"],
    ["ï½²ï¾œï¾Œï½¼ï¾ž", "Iwafidji"],
    ["ï½²ï¾œï¾Œï½¼ï¾žï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Iwafuji wheel loader"],
    ["ï½³ï½µï¾€ï¾†", "Watani"],
    ["ï½´ï½±ï¾ï¾", "Air Man"],
    ["ï½µï½°ï¾šï½¯ï½¸", "Aurec"],
    ["ï½µï½²ï½¶ï¾œ", "Oikawa"],
    ["ï½µï½¶ï¾€ï¾ž", "Okada"],
    ["ï½¶ï¾„ï½³", "Kato"],
    ["ï½¶ï¾„ï½³ ï½¸ï¾šï½°ï¾", "Kato Crane"],
    ["ï½¶ï¾œï½»ï½·", "Kawasaki"],
    ["ï½¶ï¾œï½»ï½·ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Kawasaki wheel loader"],
    ["ï½¶ï¾œï¾ï¾ž", "Kawabe"],
    ["ï½·ï½®ï½³ï½´ï½²", "Kyoei"],
    ["ï½·ï½®ï½³ï¾˜ï¾‚", "Kyoritsu"],
    ["ï½·ï½®ï½¸ï¾„ï½³ï½¶ï½²ï¾Šï¾‚", "Kyoto Hokkaido"],
    ["ï½¸ï¾Žï¾žï¾€", "Kubota"],
    ["ï½¸ï¾Žï¾žï¾€ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Kubota wheel loader"],
    ["ï½ºï½³ï¾ï¾ž", "Koube"],
    ["ï½ºï½¸ï½»ï¾(ï½¿ï¾‰ï¾€)", "Kokusan (Sonota)"],
    ["ï½ºï¾Šï¾žï½¼", "Kobashi"],
    ["ï½ºï¾ï¾žï¾™ï½º", "Kobelco"],
    ["ï½ºï¾ï¾žï¾™ï½ºï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Kobelco wheel loader"],
    ["ï½ºï¾ï¾‚", "Komatsu"],
    ["ï½ºï¾ï¾‚ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Komatsu Forklift"],
    ["ï½ºï¾ï¾‚ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Komatsu wheel loader"],
    ["ï½ºï¾ï¾‚ï¾•ï¾ï¾Žï¾ž", "Komatsu Yumbo"],
    ["ï½ºï¾‘ï½½", "Coms"],
    ["ï½»ï½¶ï½²", "Sauce"],
    ["ï½»ï½¶ï½² ï½¸ï¾šï½°ï¾", "Sakai crane"],
    ["ï½»ï½¶ï¾„", "Sakato"],
    ["ï½»ï½»ï½·", "Sasaki"],
    ["ï½»ï¾„ï½³", "Sato"],
    ["ï½»ï¾ï¾œ", "Sanwa"],
    ["ï½¼ï½ºï½¸ï½¾ï½²ï½»ï½¸ï½¼ï½®", "Shikokusai"],
    ["ï½¼ï¾Šï¾žï½³ï¾—", "Shibaura"],
    ["ï½¼ï¾ï½ºï½³", "Shinko"],
    ["ï½¼ï¾ï½ºï½³ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Shinko forklift"],
    ["ï½¼ï¾ï¾€ï¾žï½²ï¾œ", "Shindaiiwa"],
    ["ï½¼ï¾ï¾’ï½²ï¾œ", "Shinmeiwa"],
    ["ï½¼ï¾ï¾’ï½²ï¾œ ï½¸ï¾šï½°ï¾", "Shinmeiwa crane"],
    ["ï½½ï½¶ï¾žï¾‰", "Sugano"],
    ["ï½½ï¾ï¾„ï¾“", "Sumitomo"],
    ["ï½½ï¾ï¾„ï¾“ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Sumitomo Forklift"],
    ["ï½½ï¾ï¾„ï¾“ï¾•ï¾ï¾Žï¾ž", "Sumitomo Yumbo"],
    ["ï½½ï¾“ï¾„", "Smart"],
    ["ï½¾ï¾žï¾ï¾‰ï½³", "Zeno"],
    ["ï¾€ï½²ï½·", "Taiki"],
    ["ï¾€ï½²ï½·ï½®ï½¸", "Taikoku"],
    ["ï¾€ï½¶ï½·ï¾€", "Takakita"],
    ["ï¾€ï½¶ï½·ï¾ž", "Takagi"],
    ["ï¾€ï½¹ï½³ï¾", "Takeuchi"],
    ["ï¾€ï¾€ï¾žï¾‰", "Tada"],
    ["ï¾€ï¾€ï¾žï¾‰ ï½¸ï¾šï½°ï¾", "Tadano crane"],
    ["ï¾€ï¾žï½²ï¾…ï¾Šï¾Ÿï½¯ï½¸", "Dynapac"],
    ["ï¾€ï¾žï½²ï¾ï¾", "Daihen"],
    ["ï¾ï½¸ï½½ï½²", "Chikusui"],
    ["ï¾ï¾Šï¾ž", "Ciba"],
    ["ï¾‚ï¾ï¾”", "Tsuchiya"],
    ["ï¾ƒï¾žï¾ï¾–ï½°", "Denyo"],
    ["ï¾„ï½°ï½±", "Toa"],
    ["ï¾„ï½³ï½·ï½­ï½³", "Citrus fruit"],
    ["ï¾„ï½³ï½ºï½³", "Toukou"],
    ["ï¾„ï¾—ï½¸ï¾€ï½°", "Tractor"],
    ["ï¾„ï¾—ï¾ï¾ƒï½¯ï½¸ï½½", "Tortex"],
    ["ï¾…ï½¶ï¾ï¾", "Nakamichi"],
    ["ï¾…ï½¶ï¾žï¾‰", "Nagano"],
    ["ï¾…ï¾ï½¾ï½² ï½¸ï¾šï½°ï¾", "Nansei crane"],
    ["ï¾†ï½¯ï½ºï½°", "Nikko"],
    ["ï¾†ï½¯ï¾Žï¾Ÿï¾ï¾ƒï¾žï¾ï½·", "Nippondenki"],
    ["ï¾†ï½²ï½¶ï¾žï¾€", "Niigata"],
    ["ï¾†ï½¼ï½µ", "Nisio"],
    ["ï¾†ï¾ï¾•", "Nichiyu"],
    ["ï¾†ï¾ï¾•ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Nichiyu forklift"],
    ["ï¾†ï¾Œï¾Ÿï¾›", "Nipro"],
    ["ï¾†ï¾Žï¾ï½¼ï½¬ï¾˜ï½®ï½³", "Nippon Shara"],
    ["ï¾†ï¾Žï¾ï¾Œï¾™ï¾Šï½°ï¾Œ", "Nihon Fulf Ha"],
    ["ï¾Šï¾‚ï¾€", "Hutta"],
    ["ï¾Šï¾†ï½¯ï½¸ï½½", "Hannix"],
    ["ï¾Šï¾ï¾€", "Hunter"],
    ["ï¾Šï¾žï½·ï¾žï½°", "Buggy"],
    ["ï¾Šï¾žï¾›ï¾ˆï½½", "Baroness"],
    ["ï¾Šï¾žï¾ï½»ï¾žï½²", "Banzai"],
    ["ï¾Šï¾Ÿï½°ï¾‚", "Parts"],
    ["ï¾‹ï¾€ï¾", "Hitachi"],
    ["ï¾‹ï¾‰ï¾ƒï¾ž", "Hinode"],
    ["ï¾‹ï¾‰ï¾“ï¾„", "Hinomoto"],
    ["ï¾Œï½«ï½°ï½¸ï¾˜ï¾Œï¾„", "Fork lift"],
    ["ï¾Œï½¼ï¾ž", "Fuji"],
    ["ï¾Œï¾™ï½¶ï¾œ", "Furukawa"],
    ["ï¾Œï¾™ï½¶ï¾œï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Full-color wheel loader"],
    ["ï¾Žï½¸ï½´ï¾‚", "Hokuetsu"],
    ["ï¾ï½´ï¾€ï¾ž", "Maeda"],
    ["ï¾ï½´ï¾€ï¾ž ï½¸ï¾šï½°ï¾", "Maeda crane"],
    ["ï¾ï¾‚ï½¼ï¾€", "Matsushita"],
    ["ï¾ï¾‚ï¾“ï¾„", "Matsumoto"],
    ["ï¾ï¾’ï¾„ï¾—", "Mametrala"],
    ["ï¾ï¾™ï½¾ï¾žï¾", "Marzen"],
    ["ï¾ï¾™ï¾”ï¾", "Maruyama"],
    ["ï¾ï½¶ï½»", "Mikasa"],
    ["ï¾ï¾‚ï½²", "Mitsui"],
    ["ï¾ï¾‚ï½²ï¾Žï½²ï¾™ï¾›ï½°ï¾€ï¾ž", "Mitsui wheel loader"],
    ["ï¾ï¾‚ï½µï½¶ï½µï¾›ï¾", "Mitsuoka Orochi"],
    ["ï¾ï¾‚ï½µï½¶ï½¶ï¾žï¾˜ï½­ï½°", "Mitsuoka Garueu"],
    ["ï¾ï¾‚ï½µï½¶ï½¶ï¾žï¾˜ï½­ï½°2", "Mitsuoka Garris 2"],
    ["ï¾ï¾‚ï½µï½¶ï½¸ï¾—ï½¼ï½¯ï½¸", "Mitsuoka Classic"],
    ["ï¾ï¾‚ï½µï½¶ï¾‡ï½´ï¾—", "Mitsuoka Nuela"],
    ["ï¾ï¾‚ï½µï½¶ï¾‹ï¾žï½­ï½°ï¾„", "Mitsuyuka Butte"],
    ["ï¾ï¾‚ï½µï½¶ï¾—ï½²ï½¸", "Mitsuoka Like"],
    ["ï¾ï¾‚ï½µï½¶ï¾—ï½¾ï½°ï¾„ï¾ž", "Mitsuoka Lacedo"],
    ["ï¾ï¾‚ï½µï½¶ï¾šï½²", "Mitsuoka ray"],
    ["ï¾’ï½²ï½¼ï¾ž", "Mage"],
    ["ï¾’ï½²ï¾œ", "Meiwa"],
    ["ï¾“ï¾›ï½µï½¶", "Moroka"],
    ["ï¾”ï½¼ï¾›", "Yashiro"],
    ["ï¾”ï¾ï¾Š", "Yamaha"],
    ["ï¾”ï¾ï¾ï½°", "Yanmar"],
    ["ï¾•ï¾€ï¾†", "Yutani"],
    ["ï¾•ï¾†ï½¯ï½¸", "Unic"],
    ["ï¾•ï¾†ï½¯ï½¸ ï½¸ï¾šï½°ï¾", "Unic crane"],
    ["ï¾˜ï¾ï¾ƒï¾ž", "Linde"],
    ["ï¾œï½·ï¾€", "Wakita"],
    ["ï¾œï¾€ï¾…ï¾ï¾ž", "Watanabe"],
    ["ï¾œï¾„ï¾žï½³", "Wadow"],
    ["ï¾ï¾žï¾ï¾‚", "Mercedes"],
    ["ï¾ï¾žï¾ï¾‚190ï½¼ï¾˜ï½°ï½½ï¾ž", "Benz 190 series"],
    ["ï¾ï¾žï¾ï¾‚Aï½¸ï¾—ï½½", "Benz A class"],
    ["ï¾ï¾žï¾ï¾‚Bï½¸ï¾—ï½½", "Benz B class"],
    ["ï¾ï¾žï¾ï¾‚CL", "Benz CL"],
    ["ï¾ï¾žï¾ï¾‚CLA", "Benz CLA"],
    ["ï¾ï¾žï¾ï¾‚CLK", "Benz CLK"],
    ["ï¾ï¾žï¾ï¾‚CLS", "Benz CLS"],
    ["ï¾ï¾žï¾ï¾‚Cï½¸ï¾—ï½½", "Benz C Class"],
    ["ï¾ï¾žï¾ï¾‚Cï½¸ï¾—ï½½ï¾œï½ºï¾žï¾", "Benz C Class Wagon"],
    ["ï¾ï¾žï¾ï¾‚Eï½¸ï¾—ï½½", "Benz E class"],
    ["ï¾ï¾žï¾ï¾‚Eï½¸ï¾—ï½½ï¾œï½ºï¾žï¾", "Benz E class wagon"],
    ["ï¾ï¾žï¾ï¾‚GLA", "Benz GLA"],
    ["ï¾ï¾žï¾ï¾‚GLC", "Benz GLC"],
    ["ï¾ï¾žï¾ï¾‚GLE", "Benz GLE"],
    ["ï¾ï¾žï¾ï¾‚GLK", "Benz GLK"],
    ["ï¾ï¾žï¾ï¾‚GLS", "Benz GLS"],
    ["ï¾ï¾žï¾ï¾‚GLï½¸ï¾—ï½½", "Benz GL Class"],
    ["ï¾ï¾žï¾ï¾‚Gï½¸ï¾—ï½½", "Benz G Class"],
    ["ï¾ï¾žï¾ï¾‚ML", "Benz ML"],
    ["ï¾ï¾žï¾ï¾‚Rï½¸ï¾—ï½½", "Benz R Class"],
    ["ï¾ï¾žï¾ï¾‚SL", "Benz SL"],
    ["ï¾ï¾žï¾ï¾‚SLC", "Benz SLC"],
    ["ï¾ï¾žï¾ï¾‚SLK", "Benz SLK"],
    ["ï¾ï¾žï¾ï¾‚Sï½¸ï¾—ï½½", "Benz S Class"],
    ["ï¾ï¾žï¾ï¾‚Vï½¸ï¾—ï½½", "Benz V class"],
    ["ï¾ï¾žï¾ï¾‚ï½±ï½¸ï¾„ï¾›ï½½", "Benz Actoros"],
    ["ï¾ï¾žï¾ï¾‚ï¾„ï¾—ï¾ï½½ï¾Žï¾Ÿï½°ï¾€ï½°", "Benz transporter"],
    ["ï¾ï¾žï¾ï¾‚ï¾Šï¾žï¾ˆï½µ", "Benz Baneo"],
    ["ï¾ï¾žï¾ï¾‚ï¾‹ï¾žï½±ï¾‰", "Benzianovano"],

    ["ï½¼ï¾˜ï½°ï½½ï¾ž", "series"],

    ["ï¾ï¾†", "Mini"],
    ["ï½±ï½³ï¾ƒï¾žï½¨", "Audi"],

    ["VWï½³ï½¨ï¾ˆï¾ï¾žï½°ï½ºï¾ž", "VW Winnebago"],
    ["VWï½³ï¾žï½§ï¾…ï½ºï¾žï¾", "VW Vanaagon"],
    ["VWï½³ï¾žï½ªï¾ï¾„", "VW Vent"],
    ["VWï½¶ï¾™ï¾ï¾ï½·ï¾žï½±", "VW Cullman Gear"],
    ["VWï½¸ï¾›ï½½ï½ºï¾žï¾™ï¾Œ", "VW Cross Golf"],
    ["VWï½¸ï¾›ï½½ï¾Žï¾Ÿï¾›", "VW Cross Polo"],
    ["VWï½ºï¾—ï½°ï¾„ï¾ž", "VW colored"],
    ["VWï½ºï¾žï¾™ï¾Œ", "VW Golf"],
    ["VWï½ºï¾žï¾™ï¾Œ ï½µï½°ï¾™ï¾„ï¾—ï½¯ï½¸", "VW Golf All truck"],
    ["VWï½ºï¾žï¾™ï¾Œ ï¾Œï¾Ÿï¾—ï½½", "VW Golf Plus"],
    ["VWï½ºï¾žï¾™ï¾Œï½³ï¾žï½§ï¾˜ï½±ï¾ï¾„", "VW Golf Variant"],
    ["VWï½ºï¾žï¾™ï¾Œï½¶ï¾Œï¾žï¾˜ï½µï¾š", "VW Golf Convertible"],
    ["VWï½ºï¾žï¾™ï¾Œï¾„ï½©ï½°ï¾—ï¾", "VW Golf Touran"],
    ["VWï½ºï¾žï¾™ï¾Œï¾œï½ºï¾žï¾", "VW Golf Wagon"],
    ["VWï½»ï¾žï¾‹ï¾žï½°ï¾„ï¾™", "VW Xavier"],
    ["VWï½¼ï½¬ï¾—ï¾", "VW Sharan"],
    ["VWï½¼ï¾›ï½¯ï½º", "VW Siroco"],
    ["VWï½¼ï¾žï½ªï½¯ï¾€", "VW Jetta"],
    ["VWï¾ƒï½¨ï½¸ï¾žï½±ï¾", "VW Tiguan"],
    ["VWï¾„ï½©ï½±ï¾šï½¸ï¾ž", "VW Tuareg"],
    ["VWï¾†ï½­ï½°ï¾‹ï¾žï½°ï¾„ï¾™", "VW New Beetle"],
    ["VWï¾Šï¾Ÿï½»ï½°ï¾„", "VW Passat"],
    ["VWï¾Šï¾Ÿï½»ï½°ï¾„ ï½³ï¾žï½§ï¾˜ï½±ï¾ï¾„", "VW Passat Valiant"],
    ["VWï¾Šï¾Ÿï½»ï½°ï¾„ï¾œï½ºï¾žï¾", "VW Passat Wagon"],
    ["VWï¾‹ï¾žï½°ï¾„ï¾™", "VW beetle"],
    ["VWï¾Žï¾žï½°ï¾—", "VW Borer"],
    ["VWï¾Žï¾Ÿï¾›", "VW Polo"],
    ["VWï¾™ï½°ï¾€ï¾", "VW Routton"],
    ["VWï¾™ï¾Žï¾Ÿ", "VW Lupo"],
    ["ï½µï¾ï¾Ÿï¾™ ï½¼ï½¸ï¾žï¾…ï¾‘", "Opel Signum"],
    ["ï½µï¾ï¾Ÿï¾™ï½±ï½½ï¾„ï¾—", "Opel Astra"],
    ["ï½µï¾ï¾Ÿï¾™ï½±ï½½ï¾„ï¾—ï¾œï½ºï¾žï¾", "Opel Astra Wagon"],
    ["ï½µï¾ï¾Ÿï¾™ï½³ï¾žï½¨ï½°ï¾€", "Opel Vita"],
    ["ï½µï¾ï¾Ÿï¾™ï½µï¾’ï½¶ï¾ž", "Opel Omega"],
    ["ï½µï¾ï¾Ÿï¾™ï½µï¾’ï½¶ï¾žï¾œï½ºï¾žï¾", "Opel Omega Wagon"],
    ["ï½µï¾ï¾Ÿï¾™ï½¶ï¾˜ï¾Œï¾žï¾—", "Opel's Calibra"],
    ["ï½µï¾ï¾Ÿï¾™ï½»ï¾žï¾Œï½¨ï½°ï¾—", "Opel Zafira"],
    ["ï½µï¾ï¾Ÿï¾™ï¾ï¾žï½¸ï¾„ï¾—", "Opel Vectra"],
    ["ï½µï¾ï¾Ÿï¾™ï¾ï¾žï½¸ï¾„ï¾—ï¾œï½ºï¾žï¾", "Opel Victora Wagon"],
    ["ï½µï¾ï¾Ÿï¾™ï¾’ï¾˜ï½°ï¾Šï¾ž", "Opel Meriba"],
    ["ï¾Žï¾žï¾™ï¾Žï¾ž", "Volvo"],
    ["ï¾Žï¾žï¾™ï¾Žï¾žï½¸ï¾›ï½½ï½¶ï¾ï¾„ï¾˜ï½°", "Volvo cross country"],
    ["ï¾ƒï¾žï½¨ï½½ï½¶ï¾Šï¾žï¾˜ï½°", "Discovery"],
    ["ï¾ƒï¾žï½¨ï¾Œï½ªï¾ï¾€ï¾žï½°", "Defender"],
    ["ï¾Œï¾˜ï½°ï¾—ï¾ï¾€ï¾žï½°", "Freelander"],
    ["ï¾Œï¾˜ï½°ï¾—ï¾ï¾€ï¾žï½°2", "Freelander 2"],
    ["ï¾—ï¾ï¾„ï¾žï¾›ï½°ï¾Šï¾žï½°", "Land Rover"],
    ["ï¾šï¾ï½¼ï¾žï¾›ï½°ï¾Šï¾žï½°", "Range Rover"],
    ["ï¾›ï½°ï¾Šï¾žï½°", "Rover"],
    ["ï¾›ï½°ï¾Šï¾žï½°200", "Rover 200"],
    ["ï¾›ï½°ï¾Šï¾žï½°216", "Rover 216"],
    ["ï¾›ï½°ï¾Šï¾žï½°623", "Rover 623"],
    ["ï¾›ï½°ï¾Šï¾žï½°75", "Rover 75"],
    ["ï¾›ï½°ï¾Šï¾žï½°827", "Rover 827"],
    ["ï¾›ï½°ï¾Šï¾žï½°MG", "Rover MG"],
    ["ï¾›ï½°ï¾Šï¾žï½°MGF", "Rover MGF"],
    ["ï¾›ï½°ï¾Šï¾žï½°ï¾ï¾†", "Rover Mini"],

    ["GMC ï½»ï¾Šï¾žï¾…", "GMC Savannah"],
    ["GMC ï½»ï¾Œï½§ï¾˜", "GMC Safari"],
    ["GMC ï½¼ï½´ï¾—", "GMC Sierra"],
    ["GMC ï¾€ï½²ï¾Œï½°ï¾", "GMC Typhoon"],
    ["GMC ï¾Šï¾žï¾ï¾ƒï¾žï½­ï½°ï¾—", "GMC Bandura"],
    ["GMC ï¾•ï½°ï½ºï¾", "GMC Yukon"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸", "Cadillac"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ ï½±ï¾—ï¾ï¾ƒ", "Cadillac Arante"],

    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï½´ï½½ï½¶ï¾šï½°ï¾„ï¾ž", "Cadillac Escalade"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï½´ï¾™ï¾„ï¾žï¾—ï¾„ï¾ž", "Cadillac Eldorado"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï½ºï¾ï½ºï½°ï½½", "Cadillac Concourse"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï½¾ï¾‹ï¾žï¾™", "Cadillac Seville"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï¾„ï¾žï½©ï¾‹ï¾žï¾™", "Cadillac Deubil"],
    ["ï½·ï½¬ï¾ƒï¾žï¾—ï½¯ï½¸ï¾Œï¾˜ï½°ï¾„ï½³ï½¯ï¾„ï¾ž", "Cadillac Fleetwood"],
    ["ï½»ï¾€ï½°ï¾", "Saturn"],
    ["ï½¼ï¾Žï¾žï¾šï½°", "Chevrolet"],
    ["ï½¼ï¾Žï¾žï¾šï½° C1500", "Chevrolet C 1500"],
    ["ï½¼ï¾Žï¾žï¾šï½° K1500", "Chevrolet K1500"],
    ["ï½¼ï¾Žï¾žï¾šï½°HHR", "Chevrolet HHR"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½±ï½½ï¾„ï¾›", "Chevrolet Astro"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½±ï¾Šï¾žï¾—ï¾ï¾", "Chevrolet Avalanche"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½²ï¾ï¾Šï¾Ÿï¾—", "Chevrolet Impala"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½´ï½¸ï½½ï¾Œï¾Ÿï¾šï½½", "Chevrolet Express"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½µï¾Œï¾Ÿï¾„ï¾—", "Chevrolet Optra"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¶ï¾Œï¾Ÿï¾˜ï½½", "Chevrolet Caprice"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¶ï¾ï¾›", "Chevrolet Camaro"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½·ï½¬ï¾Œï¾Ÿï¾ƒï½¨ï¾Šï¾ž", "Chevrolet Captiva"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½ºï¾™ï¾ï¾žï½¯ï¾„", "Chevrolet Corvette"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½»ï¾Šï¾žï½°ï¾Šï¾žï¾", "Chevrolet Suburban"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¼ï½ªï¾‹ï¾žï½°ï¾Šï¾žï¾", "Chevy Chevy Bang"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¼ï¾™ï¾Šï¾žï¾—ï½°ï¾„ï¾ž", "Chevrolet Silverado"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï½¿ï¾†ï½¯ï½¸", "Chevrolet Sonic"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï¾€ï¾Ž", "Chevrolet Ho"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï¾„ï¾—ï¾Šï¾žï½°ï½½", "Chevrolet traverse"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï¾„ï¾šï½²ï¾™ï¾Œï¾žï¾šï½°ï½»ï¾ž", "Chevy trail beam laser"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï¾Œï¾žï¾šï½²ï½»ï¾žï½°", "Chevrolet Blazer"],
    ["ï½¼ï¾Žï¾žï¾šï½°ï¾“ï¾ï¾ƒï½¶ï¾™ï¾›", "Chevrolet Monte Carlo"],
    ["ï¾‹ï¾žï½­ï½²ï½¯ï½¸ï¾˜ï½°ï½¶ï¾žï¾™", "Buick Regal"],
    ["ï¾Žï¾Ÿï¾ï¾ƒï½¨ï½±ï½¯ï½¸ï¾Œï½§ï½²ï½¬ï½°ï¾Šï¾ž", "Pontiac Fariba"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°", "Chrysler"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°300", "Chrysler 300"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°300C", "Chrysler 300C"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°300M", "Chrysler 300M"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°PTï½¸ï¾™ï½°ï½»ï¾žï½°", "Chrysler PT Cruiser"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°ï½²ï¾Œï¾Ÿï½¼ï¾›ï¾", "Chrysler Epsilon"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°ï½¸ï¾›ï½½ï¾Œï½§ï½²ï½±", "Chrysler Cross Fire"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°ï½¸ï¾žï¾—ï¾ï¾„ï¾žï¾Žï¾žï½²", "Chrysler Grand Boy"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°ï¾ˆï½µï¾", "Chrysler neon"],
    ["ï½¸ï¾—ï½²ï½½ï¾—ï½°ï¾Žï¾žï½²ï½¼ï¾žï½¬ï½°", "Chrysler Voyager"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï½¸ï¾žï¾—ï¾ï¾„ï¾žï¾ï½ªï¾›ï½·", "Jeep Grand Cherokee"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï½ºï¾ï¾ï¾€ï¾žï½°", "Jeep Commander"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï½ºï¾ï¾Šï¾Ÿï½½", "Jeep compass"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï¾ï½ªï¾›ï½·ï½°", "Jeep Cherokee"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï¾Šï¾Ÿï¾„ï¾˜ï½µï½¯ï¾„", "Jeep Patriot"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï¾—ï¾ï½¸ï¾žï¾—ï½°", "Jeep Wrangler"],
    ["ï½¼ï¾žï½°ï¾Œï¾Ÿï¾šï¾ˆï½¹ï¾žï½°ï¾„ï¾ž", "Jeep Renegade"],
    ["ï¾€ï¾žï½¯ï½¼ï¾ž", "Dodge"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žJC", "Dodge JC"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï½±ï¾ï¾žï¾ï½¼ï¾žï½¬ï½°", "Dodge Avenger"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï½·ï½¬ï¾˜ï¾Šï¾žï½°", "Dodge Caliber"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾€ï¾žï½ºï¾€", "Dodge Dakota"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾ï½¬ï½°ï½¼ï¾žï½¬ï½°", "Dodge Charger"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾ï½¬ï¾šï¾ï½¼ï¾žï½¬ï½°", "Dodge Challenger"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾ƒï¾žï½­ï¾—ï¾ï½ºï¾ž", "Dodge Durango"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾…ï½²ï¾„ï¾›", "Dodge Nitro"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾Šï¾žï½²ï¾Šï¾Ÿï½°", "Dodge Viper"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾ï½¸ï¾žï¾…ï¾‘", "Dodge Magnum"],
    ["ï¾€ï¾žï½¯ï½¼ï¾žï¾—ï¾‘", "Dodge Ram"],
    ["J100ï¾„ï¾—ï½¯ï½¸", "J100 truck"],
    ["J80ï¾„ï¾—ï½¯ï½¸", "J80 truck"],
    ["ï½²ï½¸ï½¼ï½µï¾", "Ixion"],
    ["ï½´ï½¸ï½½ï¾ï¾Ÿï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Expedition"],
    ["ï½´ï½½ï½¹ï½°ï¾Œï¾Ÿ", "Escape"],
    ["ï½¸ï½°ï½¶ï¾ž", "Cougar"],
    ["ï½½ï¾ï¾Ÿï½¸ï¾„ï¾›ï¾", "Spectron"],
    ["ï¾ƒï¾™ï½½ï¾€ï½°", "Telstar"],
    ["ï¾ƒï¾™ï½½ï¾€ï½°â…¡", "Telstar â…¡"],
    ["ï¾ƒï¾™ï½½ï¾€ï½°ï¾œï½ºï¾žï¾", "Telstar Wagon"],
    ["ï¾Œï½ªï½½ï¾ƒï½¨ï¾Šï¾ž", "Festiva"],
    ["ï¾Œï½ªï½½ï¾ƒï½¨ï¾Šï¾žï¾ï¾†ï¾œï½ºï¾žï¾", "Festiva Mini Wagon"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž", "Ford"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž E-350", "Ford E-350"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž F-150", "Ford F-150"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž ï½´ï½ºï½½ï¾Žï¾Ÿï½°ï¾‚", "Ford Eco Sports"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž ï½´ï½ºï¾‰ï¾—ï½²ï¾", "Ford Econoline"],
    ["ï¾Œï½«ï½°ï¾„ï¾ž ï¾Œï½¨ï½´ï½½ï¾€", "Ford Fiesta"],
    ["ï¾Œï½«ï½°ï¾„ï¾žka", "Ford ka"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï½´ï½¸ï½½ï½¶ï½°ï½¼ï¾žï½®ï¾", "Ford Excursion"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï½´ï½¸ï½½ï¾Œï¾Ÿï¾›ï½°ï¾—ï½°", "Ford Explorer"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï½»ï¾ï¾€ï¾žï½°ï¾Šï¾žï½°ï¾„ï¾ž", "Ford Thunderbird"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï¾„ï½°ï¾—ï½½", "Ford Taurus"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï¾Œï½«ï½°ï½¶ï½½", "Ford Focus"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï¾Œï¾žï¾›ï¾ï½º", "Ford Bronco"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï¾ï½½ï¾€ï¾ï½¸ï¾ž", "Ford Mustang"],
    ["ï¾Œï½«ï½°ï¾„ï¾žï¾“ï¾ï¾ƒï¾žï½µ", "Ford Mondeo"],
    ["ï¾Œï¾˜ï½°ï¾€ï¾ž", "Frida"],
    ["ï¾Œï¾˜ï½°ï¾€ï¾ž ATF", "Frida ATF"],
    ["ï¾ï½°ï½·ï½­ï¾˜ï½°", "Mercury"],
    ["ï¾˜ï¾ï½¶ï½°ï¾", "Lincoln"],
    ["ï¾˜ï¾ï½¶ï½°ï¾ LS", "Lincoln LS"],
    ["ï¾˜ï¾ï½¶ï½°ï¾MKX", "Lincoln MKX"],
    ["ï¾˜ï¾ï½¶ï½°ï¾ï½±ï¾‹ï¾žï½´ï½°ï¾€ï½°", "Lincoln Aviator"],
    ["ï¾˜ï¾ï½¶ï½°ï¾ï¾€ï½³ï¾ï½¶ï½°", "Lincoln Town Car"],
    ["ï¾˜ï¾ï½¶ï½°ï¾ï¾…ï¾‹ï¾žï½¹ï¾žï½°ï¾€", "Lincoln Navigator"],
    ["ï¾˜ï¾ï½¶ï½°ï¾ï¾ï½°ï½¸8", "Lincoln Mark 8"],
    ["ï½±ï¾™ï¾Œï½§145", "Alpha 145"],
    ["ï½±ï¾™ï¾Œï½§146", "Alpha 146"],
    ["ï½±ï¾™ï¾Œï½§147", "Alpha 147"],
    ["ï½±ï¾™ï¾Œï½§155", "Alpha 155"],
    ["ï½±ï¾™ï¾Œï½§156", "Alpha 156"],
    ["ï½±ï¾™ï¾Œï½§159", "Alpha 159"],
    ["ï½±ï¾™ï¾Œï½§166", "Alpha 166"],
    ["ï½±ï¾™ï¾Œï½§GT", "Alpha GT"],
    ["ï½±ï¾™ï¾Œï½§GTV", "Alpha GTV"],
    ["ï½±ï¾™ï¾Œï½§ï½½ï¾Šï¾Ÿï½²ï¾€ï¾žï½°", "Alpha Spider"],
    ["ï½±ï¾™ï¾Œï½§ï½½ï¾Žï¾Ÿï½°ï¾‚W", "Alpha Sports W"],
    ["ï½±ï¾™ï¾Œï½§ï¾›ï¾’ï½µ", "Alfa Romeo"],
    ["ï½±ï¾™ï¾Œï½§ï¾›ï¾’ï½µ ï½¼ï¾žï½­ï¾˜ï½´ï½¯ï¾€", "Alfa Romeo Giulietta"],
    ["ï½±ï¾™ï¾Œï½§ï¾›ï¾’ï½µ ï¾Œï¾žï¾šï¾—", "Alfa Romeo Brera"],
    ["ï½±ï¾™ï¾Œï½§ï¾›ï¾’ï½µ ï¾ï¾„", "Alfa Romeo Mito"],
    ["ï½±ï½³ï¾„ï¾‹ï¾žï½±ï¾ï½·", "Out Bianchi"],
    ["ï½¸ï¾žï¾—ï¾ï¾ƒï¾žï¾Œï¾Ÿï¾ï¾„", "Grande Punto"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„", "Fiat"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ 500", "Fiat 500"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ 500C", "Fiat 500C"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ 500S", "Fiat 500S"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ 500X", "Fiat 500X"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ï¾Šï¾žï¾™ï½¹ï½¯ï¾€", "Fiat Barchetta"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ï¾Šï¾Ÿï¾ï¾€ï¾ž", "Fiat Panda"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ï¾Œï¾Ÿï¾ï¾„", "Fiat Punto"],
    ["ï¾Œï½¨ï½±ï½¯ï¾„ï¾‘ï¾™ï¾ƒï½¨ï¾Œï¾Ÿï¾—", "Fiat Multipla"],
    ["ï½¼ï¾„ï¾›ï½´ï¾ ï½¸ï¾žï¾—ï¾ï¾„ï¾žC4", "Citroen Grand C4"],
    ["ï½¼ï¾„ï¾›ï½´ï¾", "Citroen"],

    ["ï½´ï½¸ï¾žï½»ï¾žï¾ï¾ƒï½¨ï½±", "Xanthia"],
    ["ï½¸ï½»ï¾—", "Xsara"],
    ["ï½¸ï½»ï¾—ï¾‹ï¾Ÿï½¶ï½¿", "Kusara Picasso"],
    ["ï½»ï½¸ï½¿", "saxo"],
    ["ï¾Œï¾Ÿï½¼ï¾žï½®ï½°", "Peugeot"],
    ["ï¾™ï¾‰ï½°ï½±ï¾Šï¾žï¾ï¾€ï½²ï¾‘", "Renault Avan Time"],
    ["ï¾™ï¾‰ï½°ï½±ï¾™ï¾‹ï¾Ÿï½°ï¾‡", "Renault Alpine"],
    ["ï¾™ï¾‰ï½°ï½³ï½²ï¾ï¾„ï¾ž", "Renault Wind"],
    ["ï¾™ï¾‰ï½°ï½´ï½½ï¾Šï¾Ÿï½½", "Renault Espace"],
    ["ï¾™ï¾‰ï½°ï½¶ï¾ï½¸ï¾žï½°", "Renault Kangoo"],
    ["ï¾™ï¾‰ï½°ï½·ï½¬ï¾Œï¾Ÿï¾ï½¬ï½°", "Renault Capture"],
    ["ï¾™ï¾‰ï½°ï½¸ï¾žï¾—ï¾ï½¾ï¾†ï½¯ï½¸", "Renault GranSenic"],
    ["ï¾™ï¾‰ï½°ï½ºï¾šï½µï½½", "Renault Koreos"],
    ["ï¾™ï¾‰ï½°ï¾„ï½©ï½²ï¾ï½ºï¾ž", "Renault Twingo"],
    ["ï¾™ï¾‰ï½°ï¾’ï½¶ï¾žï½°ï¾‡", "Renault Megane"],
    ["ï¾™ï¾‰ï½°ï¾™ï½°ï¾ƒï½¼ï½±", "Renault Rutissia"],
    ["USï½±ï½ºï½°ï¾„ï¾žï¾œï½ºï¾žï¾", "US Accord Wagon"],
    ["USï½µï¾ƒï¾žï½¯ï½¾ï½²", "US Odyssey"],
    ["USï¾„ï¾–ï¾€ ï¾Œï¾Ÿï¾˜ï½³ï½½", "US Toyota Prius"],
    ["USï¾†ï½¯ï½»ï¾ ï¾€ï½²ï¾€ï¾", "US Nissan Titan"],
    ["ï½±ï½½ï¾„ï¾ï¾ï½°ï¾ƒï½¨ï¾", "Aston Martin"],
    ["ï½±ï½½ï¾„ï¾ï¾ï½°ï¾ƒï½¨ï¾DB7", "Aston Martin DB 7"],
    ["ï½±ï½½ï¾„ï¾ï¾ï½°ï¾ƒï½¨ï¾DB9", "Aston Martin DB 9"],
    ["ï½³ï½¨ï¾ˆï¾ï¾žï½°ï½ºï¾ž", "Winnebego"],
    ["ï½³ï½¨ï¾˜ï½½ï½¼ï¾žï½°ï¾Œï¾Ÿ", "Willis Jeep"],
    ["ï½´ï½¸ï½½ï½·ï½¬ï¾˜ï¾Šï¾žï½°", "Excalibur"],
    ["ï½·ï½±", "Kia"],
    ["ï½¹ï½°ï¾€ï¾Šï¾‘", "Caterham"],
    ["ï½»ï½°ï¾Œï¾ž9-3", "Saab 9-3"],
    ["ï½»ï½°ï¾Œï¾ž9-5", "Saab 9-5"],
    ["ï½»ï½°ï¾Œï¾ž900", "Saab 900"],
    ["ï½»ï½°ï¾Œï¾ž9000", "Saab 9000"],
    ["ï½»ï¾ï¾–ï¾", "Sanyon"],
    ["ï½¼ï½´ï¾…", "Siena"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°", "Jaguar"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°Fï¾€ï½²ï¾Œï¾Ÿ", "Jaguar F type"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°Fï¾ï¾Ÿï½°ï½½", "Jaguar F pace"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°Sï¾€ï½²ï¾Œï¾Ÿ", "Jaguar S type"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°XE", "Jaguar XE"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°XFï½¼ï¾˜ï½°ï½½ï¾ž", "Jaguar XF series"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°XJï½¼ï¾˜ï½°ï½½ï¾ž", "Jaguar XJ series"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°XKï½¼ï¾˜ï½°ï½½ï¾ž", "Jaguar XK series"],
    ["ï½¼ï¾žï½¬ï½¶ï¾žï½°Xï¾€ï½²ï¾Œï¾Ÿ", "Jaguar X type"],
    ["ï½¼ï¾žï½®ï¾ï¾ƒï¾žï½¨ï½±", "John Deere"],
    ["ï½½ï¾ï½°ï¾„", "Smart"],
    ["ï½½ï¾ï½°ï¾„ ï¾Œï½«ï½°ï¾‚ï½°", "Smart For Two"],
    ["ï½½ï¾ï½°ï¾„ ï¾Œï½«ï½°ï¾Œï½«ï½°", "Smart For Four"],
    ["ï½¾ï½ºï½²ï½±", "Sequoia"],
    ["ï½¿ï¾—ï½°ï¾—", "Solara"],
    ["ï¾€ï½ºï¾", "Tacoma"],
    ["ï¾€ï¾ï¾„ï¾žï¾—", "Tundra"],
    ["ï¾€ï¾žï½²ï¾‘ï¾—ï½°", "Daimler"],
    ["ï¾ƒï¾žï¾‹ï¾žï½¯ï¾„ï¾Œï¾žï¾—ï½³ï¾", "David Brown"],
    ["ï¾„ï¾˜ï½¶ï¾žï¾‰", "Trigano"],
    ["ï¾†ï½­ï½°ï¾Žï¾—ï¾ï¾„ï¾ž", "New Holland"],
    ["ï¾Šï¾ï½°", "Hummer"],
    ["ï¾Šï¾žï½°ï½·ï¾", "Birkin"],
    ["ï¾‹ï½­ï¾ï¾€ï¾žï½²", "Hyundai"],
    ["ï¾‹ï½­ï¾ï¾€ï¾žï½²ï½´ï¾—ï¾ï¾„ï¾—", "Hyundai Elantra"],
    ["ï¾‹ï½­ï¾ï¾€ï¾žï½²ï½¸ï¾žï¾šï¾ï½¼ï¾žï½¬ï½°", "Hyundai Granger"],
    ["ï¾‹ï½­ï¾ï¾€ï¾žï½²ï½»ï¾ï¾€ï¾Œï½ª", "Hyundai Santa Fe"],
    ["ï¾‹ï½­ï¾ï¾€ï¾žï½²ï½¿ï¾…ï¾€", "Hyundai Sonata"],
    ["ï¾Œï½ªï¾—ï½°ï¾˜", "Ferrari"],

    ["ï½¶ï¾˜ï¾Œï½«ï¾™ï¾†ï½±", "California"],
    ["ï¾ï¾žï¾ï¾„ï¾šï½°", "Bentley"],
    ["ï¾Žï½°ï¾™ï¾ƒï¾žï¾", "Holden"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ª ï¾Šï¾Ÿï¾…ï¾’ï½°ï¾—", "Porsche Panamera"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ª911", "Porsche 911"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ª928", "Porsche 928"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ª944", "Porsche 944"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ª968", "Porsche 968"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ªï½¶ï½²ï½´ï¾", "Porsche Cayenne"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ªï½¹ï½²ï¾ï¾", "Porsche Cayman"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ªï¾Žï¾žï½¸ï½½ï¾€ï½°", "Porsche Boxter"],
    ["ï¾Žï¾Ÿï¾™ï½¼ï½ªï¾ï½¶ï¾", "Porsche Makan"],
    ["ï¾ï½¯ï½¾ï½²ï¾Œï½§ï½°ï½¶ï¾žï½¿ï¾", "Massey Ferguson"],
    ["ï¾ï½¾ï¾—ï½¯ï¾ƒï½¨Gï¾„ï½©ï½°ï¾˜ï½½ï¾žï¾“", "Maserati G Turismo"],
    ["ï¾ï½¾ï¾—ï½¯ï¾ƒï½¨ï½·ï¾žï¾Œï¾žï¾˜", "Maserati Ghibli"],
    ["ï¾ï½¾ï¾—ï½¯ï¾ƒï½¨ï½¸ï½°ï¾ï¾Ÿ", "Maserati coupe"],
    ["ï¾ï½¾ï¾—ï½¯ï¾ƒï½¨ï½¸ï¾œï¾„ï¾›ï¾Žï¾Ÿï¾™ï¾ƒ", "Maserati quattro porte"],
    ["ï¾ï½¾ï¾—ï½¯ï¾ƒï½¨ï½½ï¾Šï¾Ÿï½²ï¾€ï¾žï½°", "Maserati spider"],
    ["ï¾ï¾ƒï½¨ï½½", "Matisse"],
    ["ï¾“ï½°ï½¶ï¾žï¾", "Morgan"],
    ["ï¾•ï¾†ï½­ï½³ï½¼ï½¬(ï½¿ï¾‰ï¾€)", "Unshusha (Sonota)"],
    ["ï¾—ï¾ï¾ï½± ï½²ï¾Œï¾Ÿï½¼ï¾›ï¾", "Lancia epsilon"],
    ["ï¾—ï¾ï¾ï½± ï¾ƒï½°ï¾", "Lancia Theme"],
    ["ï¾—ï¾ï¾ï½± ï¾ƒï¾žï¾™ï¾€", "Lancia delta"],
    ["ï¾—ï¾ï¾Žï¾žï¾™ï½·ï¾žï½°ï¾†", "Lamborghini"],
    ["ï¾›ï½°ï¾€ï½½ï½´ï¾˜ï½°ï½¾ï¾ž", "Lotus Elysee"],
    ["ï¾›ï½°ï¾™ï½½ï¾›ï½²ï½½", "Rolls-Royce"],
    ["ï¾›ï¾ï¾„ï¾žï¾ï¾€ï½¸ï½¼ï½°", "London taxi"],
    ["ï¾Œï¾Ÿï¾›", "Pro"],
    ["ï½±ï¾€ï½¯ï¾ï¾’ï¾ï¾„ ï½¿ï¾‰ï¾€", "Other"]
];

var gradearray = [
    ["ï½±ï¾Šï¾žï¾ï¾‚ï½§ï½°ï¾„", "Abanzator"],
    ["ï½±ï¾Šï¾žï¾ï½·ï¾žï½¬ï¾™ï¾„ï¾ž", "Avangarde"],
    ["ï½±ï¾Šï¾žï¾ï½·ï¾žï½¬ï¾™", "Avangarde"],
    ["ï½±ï¾Šï¾žï¾", "Avangarde"],
    ["ï½±ï¾™ï¾ƒï½¨ï¾’ï½²ï¾„", "Ultimate"],

    ["ï¾Œï¾Ÿï¾—ï½½ï¾žï¾", "Plasma"],
    ["ï½»ï½²ï¾„ï¾ž", "side"],
    ["ï½±ï½¸ï½¾ï½½ï½¼ï½¬", "access"],
    ["ï½±ï½¸ï½¾ï½½", "access"],

    ["ï½±ï½²ï½»ï½²ï¾„", "Eyesight"],
    ["ï½±ï½²ï¾„ï¾žï¾˜ï¾ï½¸ï¾žï½½", "Idlings"],
    ["ï½±ï½²ï¾Žï¾žï¾˜ï½°", "Ivory"],
    ["ï½±ï½´ï¾—ï½½", "Aeros"],
    ["ï½±ï½´ï¾—ï½½ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾ï¾…ï¾‹ï¾žï½½ï¾ï¾Ÿï½¼ï½¬ï¾™", "Aeros Edition Navi Special"],
    ["ï½±ï½´ï¾—ï½½ï¾šï½»ï¾žï½°", "AEROS Leather"],
    ["ï½±ï½¸ï½±ï¾Šï¾žï½°ï½¼ï¾žï½®ï¾ï½´", "Aqua Version E"],
    ["ï½±ï½¸ï½¼ï½½", "Axis"],
    ["ï½¼ï¾˜ï¾ï¾€ï¾ž", "cylinder"],
    ["ï½µï¾ï¾ƒï¾žï¾ï¾ï¾„ï¾ž", "on-demand"],
    ["ï¾„ï½¯ï¾Œï¾Ÿ", "top"],
    ["ï¾ï¾ï½¯ï½¸", "matic"],
    ["ï½±ï¾ï¾‹ï¾žï½´ï¾ï¾ƒ", "Ambient"],
    ["ï½±ï½¸ï¾ƒï½¨ï¾Œï¾ž", "active"],
    ["ï¾Œï½¨ï½°ï¾™ï¾„ï¾ž", "field"],
    ["ï½±ï½¼ï½½ï¾„", "Assist"],
    ["ï½±ï½½ï¾˜ï½°ï¾„", "Athlete"],
    ["ï½±ï¾„ï¾žï¾Šï¾žï¾ï½½", "Advance"],
    ["ï½±ï¾„ï¾žï¾Šï¾žï¾ï¾ƒï½°ï½¼ï¾ž", "Advantage"],
    ["ï½»ï½³ï¾ï¾„ï¾žï¾‹ï¾žï½°ï¾„", "Soundbeat"],
    ["ï¾—ï½²ï¾", "line"],
    ["ï½ºï½°ï½¼ï¾žï½°", "cozy"],
    ["ï½·ï½¬ï¾ï¾Šï¾žï½½", "canvas"],
    ["ï¾›ï½²ï¾”ï¾™", "Royal"],
    ["ï½µï½°ï¾™", "All"],
    ["ï¾—ï½²ï½½ï¾„ï¾", "Riston"],
    ["ï½½ï¾€ï¾ï¾„ï¾žï½µï¾Œ", "stand-off"],
    ["ï½½ï¾€ï¾ï¾„ï¾ž", "stand"],

    ["ï½±ï¾†ï¾Šï¾žï½°ï½»ï¾˜ï½°", "Anniversary"],
    ["ï½±ï¾†ï¾Šï¾žï½°", "Anniversary"],
    ["ï½±ï¾†ï¾Šï¾ž", "Anniba"],
    ["ï½¸ï¾œï¾„ï¾›", "Quattro"],
    ["ï½±ï¾Šï¾žï¾ï¾ƒ", "Avante"],
    ["ï¾›ï½°ï¾„ï¾žï¾˜ï½°", "roadly"],
    ["ï½±ï¾Œï¾žï½¿ï¾™ï½°ï¾„", "Absolute"],
    ["ï½±ï¾™ï½¶ï¾ï¾€ï½°ï¾—", "Alcantra"],
    ["ï¾ƒï¾žï½¨ï½±ï½½", "Dias"],
    ["ï½¶ï½¼ï¾žï½­ï½±ï¾™", "casual"],
    ["ï¾Šï¾Ÿï½°ï¾™", "pearl"],
    ["ï½±ï½°ï¾Šï¾žï¾", "urban"],

    ["ï½±ï¾™ï¾ƒ", "Alte"],
    ["ï½±ï¾™ï¾Œï½§", "Alpha"],
    ["ï½±ï¾™ï¾", "Aluminum"],

    ["ï½²ï¾ï¾€ï½°ï½¸ï½°ï¾—ï½°", "Intercooler"],
    ["ï½²ï¾ï¾ƒï¾žï½¨ï½ºï¾ž", "Indigo"],

    ["ï½²ï¾ï¾ƒï¾žï½¨ï½ºï¾ž", "Indigo"],
    ["ï¾Œï¾Ÿï¾—ï½½ï¾žï¾", "plasma"],
    ["ï½²ï¾ï¾ƒï¾˜ï½±", "Interior"],
    ["ï½³ï¾žï½§ï¾˜ï½±ï¾ï¾„", "Valiant"],
    ["ï½³ï½¨ï½¯ï¾„", "Wit"],
    ["ï½³ï½¨ï¾ï½¸ï¾ž", "Wing"],
    ["ï½³ï½²ï¾ï¾„ï¾žï¾‚ï½±ï¾—ï½°", "Wind tourer"],
    ["ï½³ï½ªï¾™ï½·ï½¬ï¾Œï¾ž", "Welcab"],
    ["ï½³ï½´ï¾™ï½·ï½¬ï¾Œï¾ž", "Welcab"],
    ["ï½³ï½«ï½°ï¾™ï¾…ï½¯ï¾„", "Walnut"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "package"],

    ["ï½³ï¾žï½«ï½²ï½½", "Voice"],
    ["ï½´ï½±ï½ºï¾", "AC"],
    ["ï¾Šï¾Ÿï¾œï½½ï¾ƒ", "PS"],
    ["ï½½ï¾ï¾Ÿï½¼ï½¬ï¾™", "special"],
    ["ï½½ï¾ï¾Ÿï½¼ï½¬", "special"],
    ["ï½´ï½±ï¾Œï¾žï¾šï½²ï½¸", "Air break"],
    ["ï½´ï½±ï¾›", "Aero"],
    ["ï½¼ï¾žï½¬ï½½ï¾„", "just"],
    ["ï½½ï¾€ï½²ï¾™", "style"],
    ["ï½½ï¾Žï¾Ÿï½°ï¾‚", "Sports"],
    ["ï½½ï¾Žï¾Ÿï½°ï¾ƒï½¨", "sporty"],
    ["ï¾€ï¾žï½³ï¾", "down"],
    ["ï¾‚ï½±ï¾—ï½°", "tourer"],
    ["ï½´ï½±ï¾›ï¾Šï¾Ÿ", "Aeropackage"],

    ["ï¾˜ï¾ï½¯ï½¸ï½½", "Remix"],
    ["ï½´ï½¸ï½¼ï½°ï¾„ï¾ž", "Exceed"],
    ["ï½¼ï½°ï¾„", "seat"],
    ["ï½¿ï½³ï¾ï½¬ï½¸ï½¼ï½¬", "fetcher"],
    ["ï½¿ï½³ï¾ï½¬ï½¸", "fetch"],

    ["ï½´ï½¸ï½½ï½¸ï¾™ï½°ï½¼ï¾Œï¾ž", "Exclusive"],
    ["ï½´ï½º", "Eco"],
    ["ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Edition"],
    ["ï¾†ï¾šï¾‚ï¾’", "second row"],
    ["ï½´ï¾ˆï¾ï½¬ï½°ï½¼ï¾ž", "Ene charge"],
    ["ï½´ï¾ï½°ï½¼ï¾žï½ªï¾ï½¼ï½°", "Emergency"],
    ["ï¾„ï¾žï¾šï½½ï½±ï½¯ï¾Œï¾Ÿ", "dress-up"],

    ["ï½±ï½¯ï¾Œï¾Ÿ", "up"],
    ["ï¾˜ï¾Œï¾„", "lift"],
    ["ï¾Œï¾žï¾šï½°ï½·", "brake"],
    ["ï¾Œï¾žï¾šï½°", "brake"],
    ["ï½´ï¾šï½¶ï¾žï¾ï½½", "Elegance"],
    ["ï½´ï¾ï½¼ï¾žï¾Šï¾žï½½", "Enjibus"],
    ["ï½µï½°ï½¾ï¾ï¾ƒï½¨ï½¯ï½¸", "Authentic"],

    ["ï½¶ï½°ï½ºï¾ž", "Cargo"],
    ["ï½¶ï½°ï½ºï¾žï¾ƒï¾žï¾—ï½¯ï½¸ï½½", "Cargo Deluxe"],
    ["ï½¶ï½²ï¾ƒï¾", "turning"],
    ["ï½¶ï½²ï¾ƒ", "turning"],
    ["ï½¶ï½½ï¾€ï¾‘", "Custom"],
    ["ï½¿ï¾Œï¾žï¾˜ï¾", "Sovereign"],


    ["ï¾€ï½°ï¾Žï¾ž", "turbo"],
    ["ï¾Šï¾Ÿï¾™ï½º", "Parco"],
    ["ï¾Šï½¯ï¾‹ï¾Ÿï½°", "Happy"],
    ["ï¾Šï¾Ÿï½½ï¾ƒï¾™", "Pastel"],

    ["ï¾’ï¾“ï¾˜ï½±ï¾™", "Memorial"],
    ["ï½¶ï¾žï½¿ï¾˜ï¾", "Gasoline"],
    ["ï½¶ï¾žï½¯ï¾‚", "Guts"],
    ["ï½¶ï¾Œï¾žï¾˜ï½µï¾š", "Convertible"],
    ["ï½·ï½°ï¾šï½½", "Keyless"],
    ["ï½·ï½½ï¾ï½°ï½¸", "kiss mark"],
    ["ï½·ï½¾ï¾‰ï¾", "xenon"],
    ["ï¾Œï¾Ÿï½¯ï½¼ï½­", "push"],
    ["ï½·ï½¬ï¾Œï¾ž", "cab"],
    ["ï½·ï½¬ï¾ï¾‹ï¾Ÿï¾ï½¸ï¾ž", "Camping"],
    ["ï½·ï½®ï½³ï½¶ï¾€ï¾žï¾ï¾Œï¾Ÿ", "Kyuka dump"],
    ["ï½·ï¾—ï¾’ï½·", "chrome"],
    ["ï½¸ï½°ï¾Šï¾Ÿï½°", "Cooper"],
    ["ï¾šï½°ï¾", "Lane"],
    ["ï½¸ï½°ï¾™", "Cool"],
    ["ï½½ï¾‹ï¾Ÿï¾˜ï½¯ï¾„", "spirit"],

    ["ï¾ï¾žï¾˜ï½°", "berry"],
    ["ï½¸ï¾‚ï¾›ï½·ï¾ž", "Kuroshigi"],
    ["ï½¸ï¾—ï½²ï¾ï½°", "Climber"],
    ["ï½¸ï¾—ï½¼ï½¯ï½¸", "Classic"],
    ["ï½·ï½¬ï¾‹ï¾žï¾", "cabin"],
    ["ï½¸ï¾žï¾—ï¾ï¾„ï¾ž", "grand"],
    ["ï¾—ï¾ï¾„ï¾ž", "Land"],
    ["ï½¸ï¾™ï½°ï½½ï¾ž", "cruise"],
    ["ï¾„ï¾žï½³ï½¼ï½¬", ""],
    ["ï½¸ï¾™ï¾ï½²ï½½", "wheelchair"],
    ["ä»˜", "with"],
    ["å¤–", "removed"],
    ["ï½¸ï¾›ï½½", "cross"],
    ["ï½±ï¾„ï¾žï¾ï¾žï¾ï¾ï½¬ï½°", "adventure"],
    ["ï¾ï¾žï¾ï¾ï½¬ï½°", "venture"],
    ["ï½¸ï¾›ï½½ï½µï½°ï¾Šï¾žï½°", "Crossover"],
    ["ï¾šï½»ï¾žï½°", "leather"],
    ["ï½ºï½³ï½·", "Koki"],
    ["ï½ºï½³ï½¼ï½®ï½³ï½·ï½®ï½³ï½¶ï¾€ï¾žï¾ï¾Œï¾Ÿ", "Koutouka dump"],
    ["ï½ºï½³ï½¼ï½®ï½»ï½·ï¾žï½®ï½³", "repair works"],
    ["ï¾Œï¾™ï¾ï½°ï½¸", "fullmark"],
    ["ï½¾ï¾Šï¾Ÿï¾šï½°ï¾„", "separate"],
    ["ï½ºï½³ï½¾ï½·", "rear seat"],
    ["ï½ºï¾šï½¯ï¾„", "Collet"],
    ["ï½ºï¾ï½¸ï¾˜ï½°ï¾„", "Concrete"],
    ["ä½œæ¥­è»Š", "work vehicle"],
    ["ï½ºï¾ï¾ƒï¾…å°‚ç”¨è»Š", "Container-only car"],
    ["ï½ºï¾ï¾Œï½«ï½°ï¾„", "Comfort"],
    ["ï½ºï¾ï¾Œï½«ï½°ï¾„ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "Comfort package"],

    ["ï½ºï¾ï¾Œï¾Ÿï¾šï½¯ï½»ï½°", "Compressor"],
    ["ï½»ï½²ï¾„ï¾žï¾˜ï¾Œï¾„ï½±ï½¯ï¾Œï¾Ÿï½¼ï½°ï¾„ï½¼ï½¬", "Side lift up seat"],

    ["ï½»ï¾•ï½³ï¾Šï¾Ÿï¾œï½½ï¾—", "both sides power slide"],
    ["ï½»ï¾•ï½³ï½½ï¾—", "both sides power slide"],
    ["ï½»ï¾™ï½°ï¾", "Saloon"],
    ["ï½»ï¾ï½½ï½²ï½¼ï½¬", "watering car"],
    ["ï½»ï¾ï¾Žï¾Ÿï½³ï½¶ï½²", "3 way open"],
    ["ï½»ï¾ï¾™ï½°ï¾Œï¾‚ï½·", "Sunroof"],
    ["ï½»ï¾ï¾™ï½°ï¾Œ", "Sunroof"],
    ["ï½»ï¾ï¾™", "Sunroof"],
    ["ï½¼ï½½ï¾ƒï¾‘", "System"],
    ["ï½¼ï½¯ï½¸", "Chic"],
    ["ï½¼ï¾ƒï½¨ï¾—ï¾ï¾…ï½°", "City Runner"],
    ["ï½¼ï½¬ï½°ï½¼", "Chassis"],
    ["ï½¼ï¾žï½¬ï½½ï¾Šï¾Ÿï½°", "Jasper"],
    ["ï½¼ï½¬ï¾“ï¾†", "Chamonix"],
    ["ï½¼ï¾žï½¬ï¾ï¾Žï¾ž", "Jumbo"],
    ["ï½¼ï¾žï½­ï½³ï½·ï½³ï¾ï¾Šï¾Ÿï¾ï½¼ï½¬", "Heavy machine transporter"],
    ["ï½¼ï½­ï½³ï¾ˆï¾ï½·ï¾ˆï¾ï½¼ï½¬", "Anniversary car"],
    ["ï½¼ï½­ï½³ï¾ˆï¾ï½·ï¾ˆï¾ï¾“ï¾ƒï¾žï¾™", "Anniversary model"],
    ["ï½¼ï¾žï½­ï½´ï¾—", "Jewel"],
    ["ï½¼ï¾žï½®ï½²ï¾Œï½¨ï½°ï¾™ï¾„ï¾ž", "Joyfield"],
    ["ï½¼ï¾žï½®ï½²ï¾Žï¾Ÿï½¯ï¾Œï¾Ÿï¾€ï½°ï¾Žï¾ž", "Joy Pop Turbo"],
    ["ï½¼ï½®ï½ºï¾—", "Chocolat"],
    ["ï½¼ï½®ï½ºï¾—ï¾ƒï½¨ï½´", "Chocolatier"],
    ["ï½¼ï¾žï½®ï½¼ï½­ï½¾ï½·", "passenger seat"],
    ["ï½¼ï¾žï¾ï½¶ï½²ï½¼ï½¬", "garbage car"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°", "Super"],
    ["ï½´ï½¸ï½½ï¾„ï¾—", "Extra"],
    ["ï½¼ï¾žï½®ï½²ï¾Œï½¨ï½°ï¾™ï¾„ï¾ž", "joyfield"],
    ["ï½¼ï¾ï½¸ï¾žï¾™", "single"],
    ["ï½¼ï¾žï½¬ï½½ï¾„ï¾›ï½°", "just low"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°ï¾ï½¬ï½°ï½¼ï¾žï½¬ï½°", "Supercharger"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°ï¾™ï½°ï½¾ï¾ï¾„", "Super Lucent"],
    ["ï½½ï½°ï¾Šï¾Ÿï½°ï¾›ï½°", "Super low"],

    ["ï½½ï½²ï¾ï½®ï½¸", "vertical"],
    ["ï½¹ï¾žï½°ï¾„ï¾‚ï½·", "gate"],
    ["ï½¹ï¾žï½°ï¾„", "gate"],
    ["ï½±ï½¸ï¾ƒï½¨ï¾Œï¾ž", "Active"],
    ["ï½½ï½¶ï½²ï¾Œï¾žï¾™ï½°", "Sky blue"],
    ["ï½½ï½¶ï½²ï¾™ï½°ï¾Œ", "Sky roof"],
    ["ï½½ï½¶ï½²", "Sky"],
    ["ï½½ï½¸ï½´ï½±", "Square"],
    ["ï½½ï¾€ï½²ï¾˜ï½¯ï½¼ï½­", "Stylish"],
    ["ï½½ï¾€ï½²ï¾™", "Style"],

    ["ï½½ï¾€ï¾ï¾€ï¾žï½°ï¾„ï¾ž", "Standard"],
    ["ï½½ï¾ƒï½¨ï¾ï½¸ï¾žï¾šï½°", "Stingray"],
    ["ï½½ï¾‹ï¾Ÿï¾˜ï½¯ï¾„", "Spirit"],

    ["ï½½ï¾ï¾Ÿï½¼ï½¬ï¾™", "Special"],

    ["ï½½ï¾ï¾Ÿï½¯ï½¸", "Spec"],
    ["ï½½ï¾Žï¾Ÿï½°ï¾‚", "Sports"],

    ["ï½½ï¾Žï¾Ÿï½°ï¾ƒï½¨", "Sporty"],
    ["ï½½ï¾Žï¾Ÿï¾™ï¾„", "Sport"],
    ["ï¾Œï¾Ÿï¾—ï½½", "Plus"],
    ["ï½±ï½¼ï½½ï¾„", "assist"],
    ["ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Edition"],
    ["ï½´ï¾ï¾„ï¾˜ï½°", "entry"],
    ["ï½·ï½°", "key"],
    ["ï½½ï¾€ï½²ï¾™", "style"],
    ["ï½²ï¾ï¾€ï½°ï¾…", "interna"],
    ["ï½½ï¾ï½°ï¾„", "smart"],
    ["ï½½ï¾ï½²ï¾™", "Smile"],
    ["ï½½ï¾›ï½°ï¾Šï¾Ÿï½°ï¾‚ï½·", "slope"],
    ["ï½½ï¾›ï½°ï¾Šï¾Ÿï½°", "slope"],
    ["ï½¸ï¾˜ï½°ï¾", "clean"],
    ["ï¾šï½²ï¾„ï½³", "freezer"],
    ["ï¾šï½²ï½¿ï¾žï½³", "refrigerator"],

    ["ï½±ï¾†ï¾Šï¾žï½°ï½»ï¾˜ï½°", "anniversary"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "package"],
    ["ï½¾ï½°ï¾Œï¾ƒï½¨", "Safety"],
    ["ï½¾ï½¶ï¾ï¾„ï¾ž", "Second"],
    ["ï½¾ï¾Šï¾Ÿï¾šï½°ï¾„", "Separate"],
    ["ï½¾ï¾šï½¸ï½¼ï½®ï¾", "Selection"],
    ["ï½¾ï½°ï¾Œï¾ƒï½¨", "Safety"],
    ["ï½¾ï¾šï½¸ï¾„", "Select"],
    ["ï½¾ï¾žï¾ï¾ƒï½²ï½¼ï½®ï½³ï½·ï½®ï½³ï½¶ï¾€ï¾žï¾ï¾Œï¾Ÿ", "all purpose Dump"],
    ["ï½¾ï¾žï¾ï¾ƒï½²ï½¼ï½®ï½³", "all purpose"],

    ["ãã®ä»–", "Other"],
    ["ï½¿ï¾Œï¾„", "soft"],
    ["ï¾€ï½°ï¾Žï¾ž", "Turbo"],

    ["ï¾€ï½²ï¾Œï¾Ÿ", "Type"],
    ["ï½±ï½¸ï½±", "aqua"],

    ["ï¾Œï¾Ÿï¾šï½½ï¾ƒï½°ï½¼ï¾ž", "Prestige"],
    ["ï¾€ï½²ï¾”", "tire"],
    ["ï¾€ï¾žï½¯ï½¼ï½­", "dash"],
    ["ï¾€ï¾žï¾Œï¾žï¾™", "double"],
    ["ï¾€ï¾žï¾ï½¸ï¾šï½°ï¾", "crane"],
    ["ï¾€ï¾ï½¸è»Š", "Tank car"],
    ["ï¾€ï¾žï¾ï¾Œï¾Ÿ", "dump"],
    ["ï¾ï½ªï½±", "chair"],
    ["ï¾ï½¯ï¾Œï¾Ÿé‹æ¬è»Š", "Chip Carrier"],
    ["ï¾ï½­ï½°ï¾", "tune"],
    ["ï¾Œï¾žï¾—ï½¯ï½¸", "black"],
    ["ï¾‚ï½°ï¾„ï¾", "two tone"],
    ["ï½¶ï¾—ï½°", "color"],
    ["ï¾‚ï½°ï¾˜ï¾ï½¸ï¾ž", "touring"],


    ["ï¾‚ï½±ï¾—ï½°", "Tourer"],
    ["ï¾‚ï½²ï¾ï½¶ï¾‘ï¾€ï½°ï¾Žï¾ž", "Twin cam turbo"],
    ["ï¾‚ï½²ï¾ï½½ï¾Šï¾Ÿï½°ï½¸", "Twin spark"],
    ["ï¾‚ï½²ï¾ï¾…ï¾‹ï¾ž", "Twin navi"],
    ["ï¾‚ï½²ï¾", "Twin"],
    ["ï¾ƒï¾žï½¨ï½°ï¾Šï¾ž", "Diva"],
    ["ï¾ƒï½²ï½µï¾ï¾šï½²ï¾„ï½³ï½¼ï½¬", "low temp freezer"],
    ["ï¾ƒï¾žï½»ï¾žï½²ï¾", "Design"],
    ["ï¾ƒï¾žï½½ï¾„", "Dest"],
    ["ï¾ƒï¾žï½¯ï½·", "Deck"],
    ["ï¾ƒï¾žï½­ï½°ï½¸", "Duke"],
    ["ï¾ƒï¾žï¾—ï½¸ï½¼ï½°", "Deluxe"],
    ["ï¾ƒï¾žï¾—ï½¯ï½¸ï½½", "Deluxe"],
    ["ï¾ƒï¾žï¾ï¾„ï¾žï½³", "power"],
    ["ï¾˜ï¾Œï¾„ï¾‚ï½·", "lift"],
    ["ï¾„ï¾žï½±", "door"],
    ["ï¾„ï¾‹ï¾Ÿï½¯ï½¸", "topic"],
    ["ï¾„ï¾—ï½¸ï¾€ï½°", "tractor"],
    ["ï¾„ï¾—ï½¯ï½¸", "Track"],
    ["ï¾Œï½¨ï½°ï¾™ï¾„ï¾ž", "Field"],
    ["ï¾„ï¾—ï¾ï½½ï¾Žï¾Ÿï½°ï¾€ï½°", "Transporter"],

    ["ï¾„ï¾šï½¿ï¾žï½±", "Tresor"],
    ["ï¾„ï¾šï¾ï¾„ï¾ž", "Trend"],
    ["ï¾„ï¾", "Ton"],
    ["ï¾‘ï½°ï¾ï¾™ï½°ï¾Œ", "moonroof"],



    ["ï¾…ï¾‹ï¾žï¾‚ï½·", "Navigation"],
    ["ï¾…ï¾‹ï¾žï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "Navigation package"],
    ["ï¾…ï¾ï¾Šï¾žï½°ï½·ï½®ï½³ï½¶ï¾€ï¾žï¾ï¾Œï¾Ÿ", "Number Kyuka Dump"],
    ["ï¾†ï½½ï¾“", "Nismo"],
    ["ï¾†ï¾", "seat"],
    ["ï¾‡ï½°ï¾ï¾žï¾™ï¾Šï¾žï½°ï½¸ï¾ž", "Nouvelle Bag"],
    ["ï¾ˆï½½ï¾€", "Nesta"],
    ["ï¾‰ï½³ï¾–ï½³ï½½ï¾ï¾Ÿï½¼ï½¬ï¾™", "Known Special"],
    ["ï¾Šï¾Ÿï½°ï½¸ï¾šï½°ï¾", "Park Lane"],
    ["ï¾Šï¾žï½°ï½¼ï¾žï½®ï¾", "Version"],
    ["ï¾Šï¾Ÿï½°ï¾™ï½¾ï¾šï½¸ï¾„", "Pearl Select"],


    ["ï¾Šï½²ï½³ï½ªï½²ï½½ï¾€ï½°", "Highwaystar"],
    ["ï¾Šï½²ï½³ï½ªï½²", "highway"],

    ["ï¾Œï¾Ÿï¾›ï¾Šï¾Ÿï½²ï¾›ï½¯ï¾„ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Pro Pilot Edition"],
    ["ï¾Žï¾ï¾€ï¾ž", "Honda"],
    ["ï¾Šï½²ï¾Œï¾žï¾˜ï½¯ï¾„ï¾ž", "Hybrid"],
    ["ï¾Šï½²ï¾Œï¾žï¾˜", "Hybrid"],
    ["ï¾Šï¾Œï¾žï½¯ï¾˜ï¾„ï¾ž", "Hybrid"],
    ["ï¾Šï½²ï¾—ï½²ï¾", "High Line"],
    ["ï¾Šï½²ï¾™ï½°ï¾Œ", "High roof"],
    ["ï¾šï¾ƒï¾žï½¨", "ready"],
    ["ï¾Šï¾žï½·ï½­ï½°ï¾‘ï½¶ï½°", "Vacuum car"],

    ["ï¾Šï¾žï½½", "bus"],
    ["ï¾Šï¾Ÿï½¯ï½¶ï½°", "Packer"],
    ["ï¾Šï¾Ÿï½¯ï½¸", "pack"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "package"],

    ["ï¾Šï¾Ÿï½¹", "package"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾žï½½ï½¶ï½²ï¾Œï¾žï¾™ï½°", "Package Sky Blue"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾žï¾„ï¾", "Package ton"],
    ["ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾žï¾—ï¾ï¾žï¾ï¾€ï¾žï½°ï½´ï¾ƒï¾ž", "Package Lavender Eden"],
    ["ï¾Šï¾Ÿï½¯ï½¼ï½®ï¾ˆï½°ï¾„ï¾Œï¾žï¾—ï½¯ï½¸ï½²ï¾ï¾ƒï¾˜ï½±", "Passionate black interior"],
    ["ï¾Šï¾Ÿï¾ˆï¾™ï¾Šï¾žï¾", "Panel vans"],


    ["ï¾Šï¾Ÿï¾œï½°ï½½ï¾—ï½²ï¾„ï¾žï¾„", "Power slide"],
    ["ï¾Šï¾Ÿï¾œï½°ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "Power package"],
    ["ï¾Šï¾Ÿï¾œï½½ï¾ƒ", "Power steering"],
    ["ï¾Šï¾Ÿï¾œï½½ï¾—", "Power slide"],

    ["ï¾Šï¾ï½¼ï½¬ï½¹ï¾žï¾ï¾ƒï½²ï½¼ï½¬", "Limited sale"],
    ["ï¾‹ï¾Ÿï½º", "Pico"],
    ["ï¾‹ï¾žï¾€ï½°", "Bitter"],
    ["ï¾‹ï¾€ï¾žï¾˜ï¾Šï¾ï¾„ï¾žï¾™", "Hidden handle"],
    ["ï¾‹ï¾žï½¯ï½¸ï¾žï½»ï¾‘", "Big Sam"],
    ["ï¾‹ï¾—", "flat"],
    ["ï¾‹ï¾—ï¾Žï¾žï¾ƒï¾žï½¨ï½°", "flat"],
    ["ï¾‹ï¾—ï¾Žï¾žï¾ƒï¾žï½¨ï¾Žï¾›", "flat hollow"],
    ["ï¾Œï½§ï½²ï¾", "Fine"],
    ["ï¾Œï½¸ï½¼ï½¼ï½¬ï¾˜ï½®ï½³", "Welfare"],
    ["ï¾Œï½¯ï½¸ï½²ï¾", "Hook in"],
    ["ï¾Œï¾Ÿï¾—ï½½", "Plus"],
    ["ï¾Œï¾Ÿï¾—ï½½ï¾žï¾", "Plasma"],
    ["ï¾Œï¾Ÿï¾—ï¾€ï¾…", "Platana"],

    ["ï¾Œï¾Ÿï¾—ï¾ï¾…ï½¾ï¾šï½¸ï½¼ï½®ï¾", "Platinum Selection"],
    ["ï¾Œï¾Ÿï¾—ï¾ï¾…", "Platinum"],


    ["ï¾Œï¾žï¾—ï¾Žï¾žï½°", "Bravo"],
    ["ï¾Œï¾žï¾—ï¾ï¾ï¾žï½°ï½¼ï¾žï½­ï½¾ï¾šï½¸ï½¼ï½®", "Bran beige selection"],
    ["ï¾Œï¾žï¾—ï¾ï¾ï¾žï½°ï½¼ï¾žï½­ï½¾ï¾šï½¸ï½¼ï½®ï¾", "Bran beige selection"],
    ["ï¾Œï¾˜ï½°ï½½ï¾€ï½²ï¾™ï¾œï½°ï¾™ï¾„ï¾žï½¶ï½¯ï¾Œï¾Ÿ", "Freestyle World Cup"],
    ["ï¾Œï¾žï¾™ï½°ï¾‘ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Bloom Edition"],


    ["ï½·ï½®ï½³ï½¶ï¾€ï¾žï¾ï¾Œï¾Ÿ", "reinforced dump"],
    ["ï¾…ï¾ï¾Šï¾žï½°", "number"],


    ["ï¾Œï¾Ÿï¾šï½²ï¾Œï¾™", "Playfull"],
    ["ï¾Œï¾™", "full"],
    ["ï¾Œï¾Ÿï¾šï½½ï¾ƒï½°ï½¼ï¾ž", "Prestige"],
    ["ï¾Œï¾Ÿï¾šï¾ï½±ï¾‘ï½±ï¾™ï½¶", "Premium Alka"],
    ["ï¾Œï¾Ÿï¾šï¾ï½±ï¾‘", "Premium"],

    ["ï¾Œï¾Ÿï¾šï¾ï½±", "Premier"],
    ["ï¾Œï¾Ÿï¾›", "Pro"],
    ["ï¾Œï¾›ï½°ï¾˜ï¾ï½¸ï¾žï¾Œï¾›ï½±", "Flooring"],
    ["ï¾Œï¾Ÿï¾›ï½±ï½¸ï¾ƒï½¨ï¾Œï¾ž", "Proactive"],
    ["ï¾Œï¾žï¾›ï½±ï¾‘", "Bloam"],
    ["ï¾Œï¾Ÿï¾›ï½¸ï¾žï¾šï½½", "Progress"],
    ["ï¾Œï¾›ï¾ï¾ƒï½¨ï½±", "Frontier"],
    ["ï¾—ï½¸ï½¾ï¾žï½°ï¾™", "Luxel"],
    ["ï¾—ï½¸ï¾žï½¾ï¾žï½°ï¾™", "Luxel"],

    ["ï¾„ï½¸ï¾ï¾žï¾‚", "special"],
    ["ï½¼ï¾–ï½³", "utility"],

    ["ï¾ï¾žï½°ï½½", "base"],
    ["ï½¸ï¾žï¾šï½°ï¾„ï¾ž", "grade"],
    ["ï½¸ï¾žï¾—ï¾ï¾ƒï¾ž", "Grande"],
    ["ï¾ï¾Ÿï½±", "Pair"],
    ["ï¾ï¾žï¾™ï¾ƒï½¯ï½¸ï½½", "Vertex"],


    ["ï¾Žï½²ï¾™ï½¸ï¾šï½°ï¾", "Wheel crane"],
    ["ï¾Žï½³ï½¶ï½²", "hokay"],
    ["ï¾Žï¾Ÿï½³ï½¶ï½²", "pokai"],
    ["ï¾Žï¾šï½²ï½¼ï½¬", "Freezer"],
    ["ï¾Žï¾ï¾€ï¾žï½¾ï¾ï½¼ï¾ï½¸ï¾ž", "Honda sensing"],
    ["ï¾ï½²ï½¸ï¾›ï¾Šï¾žï½½", "Mini bus"],
    ["ï¾ï½²ï½ºï½°ï¾ƒï¾ž", "My coode"],
    ["ï¾ï½²ï¾›ï½°ï¾„ï¾ž", "My Road"],
    ["ï¾ï½°ï¾Œï¾ž", "Mieve"],
    ["ï¾ï½·ï½»ï½°", "Mixer"],
    ["ï¾ï¾†ï½¸ï½°ï¾Šï¾Ÿï½°", "Mini Cooper"],
    ["ï¾ï¾†ï¾—ï½²ï¾„ï½½ï¾ï¾Ÿï½¼ï½¬ï¾™", "Minilite special"],
    ["ï¾ï¾—ï¾‰", "Milano"],
    ["ï¾ï¾šï¾ƒï¾žï½¨", "Milady"],
    ["ï¾‘ï½°ï¾Œï¾žï½±ï½¯ï¾Œï¾Ÿ!", "Move up!"],
    ["ï¾’ï½²ï½¸ï½±ï½¯ï¾Œï¾Ÿ", "Make-up"],
    ["ï¾’ï½²ï¾Œï½ªï½±", "Mayfair"],
    ["ï¾’ï¾€ï¾žï¾˜ï½½ï¾„", "Medalist"],
    ["ï¾’ï¾‡ï½´ï½¯ï¾„", "Minuet"],
    ["ï¾’ï¾“ï¾˜ï½±ï¾™ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾", "Memorial Edition"],
    ["ï¾’ï¾“ï¾˜ï½±ï¾™ï½´ï¾ƒï¾žï½¨ï½¼ï½®ï¾ï¾Šï¾Ÿï½¯ï½¹ï½°ï½¼ï¾ž", "Memorial Edition Package"],
    ["ï¾“ï½°ï¾„ï¾ž", "Mode"],
    ["ï¾Šï¾Ÿï½¯ï½¹", "package"],
    ["ï¾“ï½¶", "Mocha"],
    ["ï¾“ï¾ƒï¾žï¾˜", "Model"],
    ["ï¾“ï¾ƒï¾žï¾™ï¾‰", "Moderno"],
    ["ï¾“ï¾ƒï¾žï¾™", "Model"],
    ["ï¾“ï¾•", "Mule"],
    ["ï¾•ï½°ï¾›", "Euro"],
    ["ï¾•ï¾†ï½¯ï½¸", "Unic"],
    ["ï¾•ï¾™ï¾˜", "Yururi"],
    ["ï¾—ï½²ï¾€ï¾žï½°", "Rider"],
    ["ï¾—ï½²ï¾—", "Laila"],
    ["ï¾—ï¾˜ï½°ï½±ï½°ï¾„", "Rally art"],
    ["ï¾˜ï½±ï¾™ï¾€ï½²ï¾‘", "Real time"],
    ["ï¾˜ï½¿ï¾žï½°ï¾„ï¾—ï¾ï¾…ï½°", "Resort runner"],
    ["ï¾˜ï¾‹ï¾žï¾ï½¸ï¾ž", "Living"],

    ["ï¾˜ï¾ï¾ƒï½¯ï¾„ï¾ž", "Limited"],
    ["ï¾˜ï¾ï¾ƒï½¯ï¾„", "Limited"],
    ["ï¾˜ï¾”", ""],
    ["ï¾˜ï½®ï½³ï½¶ï¾žï¾œï½½ï¾—", "Both side power slide"],
    ["ï¾˜ï½®ï½³ï½¶ï¾žï¾œï¾Šï¾Ÿï¾œ", "Both side power slide"],
    ["ï¾˜ï¾—ï½¯ï½¸ï½½", "Relax"],

    ["ï¾Šï½²ï¾Šï¾Ÿï½°", "Hyper"],
    ["ï½¼ï¾žï½®ï½²ï¾", "Join"],

    ["ï¾™ï½°ï¾„", "Root"],
    ["ï½¼ï½®ï½°ï¾„", "Short"],
    ["ï¾šï½°ï¾€ï¾žï½°", "Radar"],
    ["ï¾šï½²ï½·ï½­ï½³ï½¼ï½¬", "hearse"],
    ["ï¾šï½²ï¾„ï½³ï½¼ï½¬", "freezer"],
    ["ï¾šï¾ˆï½¹ï¾žï½°ï¾„ï¾ž", "Renegade"],
    ["ï¾›ï½°ï¾€ï¾žï½³ï¾", "Lowdown"],
    ["ï¾ï¾žï½°ï½¼ï½¯ï½¸", "Basic"],
    ["ï¾›ï½°ï¾ƒï¾žï½½ï¾„", "Rodest"],

    ["ï¾›ï½°ï¾„ï¾žï½½ï¾€ï½°", "Roadster"],

    ["ï¾œï½²ï¾™ï¾„ï¾žï½³ï½¨ï¾ï¾„ï¾ž", "Wild Wind"],
    ["ï¾œï½²ï¾™ï¾„ï¾žï½³ï½²ï¾ï¾„ï¾ž", "Wild Wind"],

    ["ï¾œï¾ï¾€ï½¯ï¾", "One Touch"],
    ["ï¾œï¾", "One"],
    ["ï¾œï¾ï¾€ï¾žï¾Œï¾™", "wonderful"],
    ["å†·è”µãƒ»å†·å‡è»Š", "Refrigerated cars"],
    ["å¡µèŠ¥è»Š", "Packer"],
    ["å¹Œè»Š", "Hood car"],
    ["å¹³ï¾Žï¾žï¾ƒï¾žï½¨", "Flat body"],
    ["æ•£æ°´è»Š", "Watering car"],
    ["æž¶ç·šä¿®ç†è»Š", "Overhead wire repair vehicle"],
    ["æž¶è£…", "body work"],
    ["æ¶ˆé˜²è»Š", "Fire engine"],
    ["æ¸…æŽƒè»Š", "Sweeping car"],
    ["ç©´æŽ˜å»ºæŸ±è»Š", "Pit excavated car"],
    ["ç²‰ç²’ä½“é‹æ¬è»Š", "Powder Transport Vehicle"],
    ["è»Šè¼›é‹æ¬è»Š", "vehicle transporter"],
    ["é“è·¯ä½œæ¥­è»Š", "Road working vehicle"],
    ["é‡æ©Ÿé‹æ¬è»Š", "Heavy equipment transporter"],
    ["é«˜æ‰€ä½œæ¥­è»Š", "Aerial work vehicle"],

    ["ï¾…ï¾‹ï¾ž", "Navigation"],
    ["ï¾…ï¾‹", "Navigation"],
    ["ï¾“ï½°ï½¼ï½®ï¾", "motion"],
    ["ï¾ƒï½¸ï¾‰ï¾›ï½¼ï¾žï½°", "technology"],
    ["ï¾ƒï½¯ï½¸", "tech"],
    ["ï¾ï¾ž", "Base"],
    ["ï¾Šï¾Ÿï¾Œï½«ï½°ï¾", "performance"],
    ["ï¾Šï¾žï¾", "van"],
    ["ï½´ï¾Žï¾žï¾˜ï½­ï½°ï½¼ï½®ï¾", "evolution"],
    ["ï½½ï¾Šï¾Ÿï½°ï¾€ï¾ž", "spada"],
    ["ï¾Œï¾žï¾™ï½°", "blue"],
    ["ï½´ï¾Œï½¨ï½¼ï½ªï¾ï½¼ï½°", "efficiency"],
    ["ï¾Šï½²ï½³ï½´ï½²ï½½ï¾€ï½°", "Highwaystar"],
    ["ï¾Œï½§ï½²ï¾", "fine"],
    ["ï½·ï¾žï½±", "gear"],
    ["ï¾Œï¾žï¾—ï¾", "blanc"],
    ["ï¾ï¾žï½°ï½¼ï¾žï½­", "beige"],
    ["ï½¾ï¾šï¾ï½¼ï½±", "Serencia"],
    ["ï½¾ï¾šï½¸", "selection"],
    ["ï½¾ï¾š", "selection"],
    ["ï¾ï¾†", "mini"],
    ["ï½·ï¾ˆï¾", "kinen"],
    ["ï¾Œï¾Ÿï¾—ï½²ï¾‘", "prime"],
    ["ï½¼ï¾žï½®ï½²ï¾Žï¾Ÿï½¯ï¾Œï¾Ÿ", "joypop"],
    ["ï½¼ï½°ï¾€ï½°", "seater"],
    ["ï¾—ï¾Œï½¨ï½¯ï¾„", "Lafite"],
    ["ï¾Šï¾žï½¯ï½¸", "back"],
    ["ï¾‰ï¾˜", ""],
    ["ï¾Šï¾Ÿï¾œï½°", "Power"],
    ["ï¾…ï¾ï¾Šï¾žï½°", "number"],
    ["ï¾›ï¾ï½¸ï¾ž", "Long"],
    ["ï¾œï½²ï½½ï¾ž", "wise"],
    ["ï¾œï½²ï¾„ï¾ž", "Wide"],
    ["ï½½ï¾Žï¾Ÿ", "sport"],
    ["ï½´ï¾Œï½¨ï½¼ï½ªï¾ï½¼ï½´ï¾šï½¶ï¾ï½½", "efficiency elegance"],
    ["ï½´ï¾Œï½¨ï½¼ï½ªï¾ï½¼ï½°", "efficiency"],
    ["ï½´ï¾Œï½¨ï½¼ï½ªï¾ï½¼", "efficiency"],
    ["ï½´ï¾Œï½¨ï½¼ï½ªï¾", "efficiency"],
    ["ï¾„ï¾šï¾ï¾„ï¾ž", "trend"],
    ["ï¾‹ï¾žï½¼ï¾žï¾ˆï½½", "business"],
    ["ï¾™ï¾ï½´ï½°ï¾™", "LumiÃ¨re"],
    ["ï¾Œï¾Ÿï¾™ï¾˜ï½´ï¾™", "Pluriel"],

    ["ï¾—ï½¸ï¾žï½¼ï¾žï½­ï½±ï¾˜", "luxury"],
    ["ï½ºï¾ï¾Œï¾Ÿ", "Compressor"],
    ["ï½µï½°ï¾„", "Auto"],
    ["ï½½ï¾„ï½¯ï¾Œï¾Ÿ", "stop"],
    ["ï½ºï¾žï½°", "go"],
    ["ï¾Žï¾œï½²ï¾„", "white"],
    ["ï½¸ï¾˜ï½¯ï¾Šï¾Ÿï½°", "Clipper"],
    ["ï½¸ï¾›", "black"]



];

function convertKanaF2H(str) {
    str = replaceStringByArrayOfIndex(str, WKANA, HKANA);
    return str;
}

function replaceStringByArrayOfIndex(str, src, dest) {
    var len = src.length;
    for (var i = 0; i < len; i++) {
        str = replaceAll(str, src[i], dest[i]);
    }
    return str;
}

function replaceAll(target, from, to) {
    if (target.indexOf(from) < 0) {
        return target;
    } else {
        return target.split(from).join(to)
    }
}

var HKANA = new Array(
    "ï½¶ï¾ž", "ï½·ï¾ž", "ï½¸ï¾ž", "ï½¹ï¾ž", "ï½ºï¾ž", "ï½»ï¾ž", "ï½¼ï¾ž", "ï½½ï¾ž", "ï½¾ï¾ž", "ï½¿ï¾ž",
    "ï¾€ï¾ž", "ï¾ï¾ž", "ï¾‚ï¾ž", "ï¾ƒï¾ž", "ï¾„ï¾ž", "ï¾Šï¾ž", "ï¾‹ï¾ž", "ï¾Œï¾ž", "ï¾ï¾ž", "ï¾Žï¾ž", "ï½³ï¾ž",
    "ï¾Šï¾Ÿ", "ï¾‹ï¾Ÿ", "ï¾Œï¾Ÿ", "ï¾ï¾Ÿ", "ï¾Žï¾Ÿ",
    "ï½§", "ï½¨", "ï½©", "ï½ª", "ï½«", "ï½¬", "ï½­", "ï½®", "ï½¯", "ï½°", "",
    "ï½±", "ï½²", "ï½³", "ï½´", "ï½µ", "ï½¶", "ï½·", "ï½¸", "ï½¹", "ï½º",
    "ï½»", "ï½¼", "ï½½", "ï½¾", "ï½¿", "ï¾€", "ï¾", "ï¾‚", "ï¾ƒ", "ï¾„",
    "ï¾…", "ï¾†", "ï¾‡", "ï¾ˆ", "ï¾‰", "ï¾Š", "ï¾‹", "ï¾Œ", "ï¾", "ï¾Ž",
    "ï¾", "ï¾", "ï¾‘", "ï¾’", "ï¾“", "ï¾”", "ï¾•", "ï¾–",
    "ï¾—", "ï¾˜", "ï¾™", "ï¾š", "ï¾›", "ï¾œ", "", "ï½¦", "", "ï¾",
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
);

var WKANA = new Array(
    "ã‚¬", "ã‚®", "ã‚°", "ã‚²", "ã‚´", "ã‚¶", "ã‚¸", "ã‚º", "ã‚¼", "ã‚¾",
    "ãƒ€", "ãƒ‚", "ãƒ…", "ãƒ‡", "ãƒ‰", "ãƒ", "ãƒ“", "ãƒ–", "ãƒ™", "ãƒœ", "ãƒ´",
    "ãƒ‘", "ãƒ”", "ãƒ—", "ãƒš", "ãƒ",
    "ã‚¡", "ã‚£", "ã‚¥", "ã‚§", "ã‚©", "ãƒ£", "ãƒ¥", "ãƒ§", "ãƒƒ", "ãƒ¼", "ãƒ®",
    "ã‚¢", "ã‚¤", "ã‚¦", "ã‚¨", "ã‚ª", "ã‚«", "ã‚­", "ã‚¯", "ã‚±", "ã‚³",
    "ã‚µ", "ã‚·", "ã‚¹", "ã‚»", "ã‚½", "ã‚¿", "ãƒ", "ãƒ„", "ãƒ†", "ãƒˆ",
    "ãƒŠ", "ãƒ‹", "ãƒŒ", "ãƒ", "ãƒŽ", "ãƒ", "ãƒ’", "ãƒ•", "ãƒ˜", "ãƒ›",
    "ãƒž", "ãƒŸ", "ãƒ ", "ãƒ¡", "ãƒ¢", "ãƒ¤", "ãƒ¦", "ãƒ¨",
    "ãƒ©", "ãƒª", "ãƒ«", "ãƒ¬", "ãƒ­", "ãƒ¯", "ãƒ°", "ãƒ²", "ãƒ±", "ãƒ³",
    "ï¼", "ï¼‘", "ï¼’", "ï¼“", "ï¼”", "ï¼•", "ï¼–", "ï¼—", "ï¼˜", "ï¼™", "ï¼¡", "ï¼¢", "ï¼£", "ï¼¤", "ï¼¥", "ï¼¦", "ï¼§", "ï¼¨", "ï¼©", "ï¼ª", "ï¼«", "ï¼¬", "ï¼­", "ï¼®", "ï¼¯", "ï¼°", "ï¼±", "ï¼²", "ï¼³", "ï¼´", "ï¼µ", "ï¼¶", "ï¼·", "ï¼¸", "ï¼¹", "ï¼º",
    "ï½", "ï½‚", "ï½ƒ", "ï½„", "ï½…", "ï½†", "ï½‡", "ï½ˆ", "ï½‰", "ï½Š", "ï½‹", "ï½Œ", "ï½", "ï½Ž", "ï½", "ï½", "ï½‘", "ï½’", "ï½“", "ï½”", "ï½•", "ï½–", "ï½—", "ï½˜", "ï½™", "ï½š"
);


console.log("iaucmap fully initiated");
